# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 10:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import signbank.video.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(storage=signbank.video.models.GlossVideoStorage(), upload_to=b'glossvideo', verbose_name=b'video file')),
                ('version', models.IntegerField(default=0, verbose_name=b'Version')),
                ('gloss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Gloss')),
            ],
        ),
        migrations.CreateModel(
            name='GlossVideoHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[(b'delete', b'delete'), (b'upload', b'upload'), (b'rename', b'rename'), (b'watch', b'watch')], default=b'watch', max_length=6, verbose_name=b'Video History Action')),
                ('datestamp', models.DateTimeField(auto_now_add=True, verbose_name=b'Date and time of action')),
                ('uploadfile', models.TextField(default=b'(not specified)', verbose_name=b'User upload path')),
                ('goal_location', models.TextField(default=b'(not specified)', verbose_name=b'Full target path')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gloss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Gloss')),
            ],
            options={
                'ordering': ['datestamp'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(upload_to=b'upload', verbose_name=b'Video file in h264 mp4 format')),
            ],
        ),
    ]
