# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import signbank.video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossvideo',
            name='version',
            field=models.IntegerField(default=0, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='glossvideo',
            name='videofile',
            field=models.FileField(storage=signbank.video.models.GlossVideoStorage(), upload_to='glossvideo', verbose_name='video file'),
        ),
        migrations.AlterField(
            model_name='glossvideohistory',
            name='action',
            field=models.CharField(choices=[('delete', 'delete'), ('upload', 'upload'), ('rename', 'rename'), ('watch', 'watch')], default='watch', max_length=6, verbose_name='Video History Action'),
        ),
        migrations.AlterField(
            model_name='glossvideohistory',
            name='datestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date and time of action'),
        ),
        migrations.AlterField(
            model_name='glossvideohistory',
            name='goal_location',
            field=models.TextField(default='(not specified)', verbose_name='Full target path'),
        ),
        migrations.AlterField(
            model_name='glossvideohistory',
            name='uploadfile',
            field=models.TextField(default='(not specified)', verbose_name='User upload path'),
        ),
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(upload_to='upload', verbose_name='Video file in h264 mp4 format'),
        ),
    ]
