# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import signbank.video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20190603_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossvideo',
            name='videofile',
            field=models.FileField(storage=signbank.video.models.GlossVideoStorage(), upload_to=signbank.video.models.get_video_file_path, validators=[signbank.video.models.validate_file_extension], verbose_name='video file'),
        ),
    ]
