# Generated by Django 4.1.7 on 2023-06-08 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import signbank.video.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0072_examplesentence_alter_translation_unique_together_and_more'),
        ('video', '0004_auto_20191120_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleVideoHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('delete', 'delete'), ('upload', 'upload'), ('rename', 'rename'), ('watch', 'watch')], default='watch', max_length=6, verbose_name='Video History Action')),
                ('datestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of action')),
                ('uploadfile', models.TextField(default='(not specified)', verbose_name='User upload path')),
                ('goal_location', models.TextField(default='(not specified)', verbose_name='Full target path')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('examplesentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.examplesentence')),
            ],
            options={
                'ordering': ['datestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExampleVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(storage=signbank.video.models.GlossVideoStorage(), upload_to=signbank.video.models.get_sentence_video_file_path, validators=[signbank.video.models.validate_file_extension], verbose_name='video file')),
                ('version', models.IntegerField(default=0, verbose_name='Version')),
                ('examplesentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.examplesentence')),
            ],
        ),
    ]
