# Generated by Django 4.2.10 on 2024-03-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_examplevideohistory_examplevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplevideohistory',
            name='action',
            field=models.CharField(choices=[('delete', 'delete'), ('upload', 'upload'), ('rename', 'rename'), ('watch', 'watch'), ('import', 'import')], default='watch', max_length=6, verbose_name='Video History Action'),
        ),
        migrations.AlterField(
            model_name='glossvideohistory',
            name='action',
            field=models.CharField(choices=[('delete', 'delete'), ('upload', 'upload'), ('rename', 'rename'), ('watch', 'watch'), ('import', 'import')], default='watch', max_length=6, verbose_name='Video History Action'),
        ),
    ]
