# Generated by Django 4.2.10 on 2024-04-24 14:14

from django.db import migrations, models
import django.db.models.deletion
import signbank.video.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0081_annotatedsentence_annotatedsentencetranslation_and_more'),
        ('video', '0006_alter_examplevideohistory_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotatedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(storage=signbank.video.models.GlossVideoStorage(), upload_to=signbank.video.models.get_annotated_video_file_path, validators=[signbank.video.models.validate_file_extension], verbose_name='video file')),
                ('eaffile', models.FileField(storage=signbank.video.models.GlossVideoStorage(), upload_to=signbank.video.models.get_annotated_video_file_path, verbose_name='eaf file')),
                ('version', models.IntegerField(default=0, verbose_name='Version')),
                ('annotatedsentence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dictionary.annotatedsentence')),
            ],
        ),
    ]
