# Generated by Django 4.2.10 on 2024-05-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_annotatedvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedvideo',
            name='corpus',
            field=models.TextField(default=''),
        ),
    ]
