# Generated by Django 4.2.11 on 2024-06-12 08:56

from django.db import migrations, models
import signbank.video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_glossvideonme_glossvideodescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AlterModelOptions(
            name='glossvideonme',
            options={'ordering': ['offset'], 'verbose_name': 'NME Gloss Video'},
        ),
        migrations.AlterField(
            model_name='glossvideo',
            name='videofile',
            field=models.FileField(storage=signbank.video.models.GlossVideoStorage(), upload_to='', validators=[signbank.video.models.validate_file_extension], verbose_name='video file'),
        ),
    ]
