# Generated by Django 4.2.10 on 2024-09-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_remove_annotatedvideo_corpus_annotatedvideo_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedvideo',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
