# Generated by Django 4.2.15 on 2024-09-23 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_remove_annotatedvideo_corpus_annotatedvideo_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossVideoPerspective',
            fields=[
                ('glossvideo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='video.glossvideo')),
                ('perspective', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=20)),
            ],
            options={
                'verbose_name': 'Gloss Video Perspective',
                'ordering': ['perspective'],
            },
            bases=('video.glossvideo',),
        ),
    ]
