# Generated by Django 4.2.10 on 2024-10-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_glossvideoperspective'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedvideo',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
