# Generated by Django 4.2.17 on 2024-12-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_annotatedvideo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossvideonme',
            name='perspective',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='center', max_length=20),
        ),
    ]
