# Generated by Django 4.2.28 on 2026-03-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_glossvideonme_perspective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossvideonme',
            name='perspective',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='', max_length=20),
        ),
    ]
