# Generated by Django 4.2.30 on 2026-07-06 10:52

from django.db import migrations, models
import django.db.models.deletion
import signbank.video.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0097_alter_gloss_absorifing_alter_gloss_absoripalm_and_more'),
        ('video', '0015_alter_glossvideonme_perspective'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonologicalVariationVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(storage=signbank.video.models.GlossVideoStorage(), upload_to='', validators=[signbank.video.models.validate_file_extension], verbose_name='video file')),
                ('version', models.IntegerField(default=0, verbose_name='Version')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.phonologicalvariation')),
            ],
        ),
    ]
