# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='role',
            field=models.CharField(choices=[('note', 'Note'), ('privatenote', 'Private Note'), ('phon', 'Phonology'), ('todo', 'To Do'), ('sugg', 'Suggestion for other gloss'), ('disc', 'Discuss between annotators'), ('ety', 'Etymology')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='deletedglossormedia',
            name='annotation_idgloss',
            field=models.CharField(max_length=30, verbose_name='Annotation ID Gloss: Dutch'),
        ),
        migrations.AlterField(
            model_name='deletedglossormedia',
            name='idgloss',
            field=models.CharField(max_length=50, verbose_name='ID Gloss'),
        ),
        migrations.AlterField(
            model_name='deletedglossormedia',
            name='item_type',
            field=models.CharField(choices=[('gloss', 'gloss'), ('image', 'image'), ('video', 'video')], max_length=5),
        ),
        migrations.AlterField(
            model_name='fieldchoice',
            name='machine_value',
            field=models.IntegerField(help_text='The actual numeric value stored in the database. Created automatically.'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='absOriFing',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Absolute Orientation: Fingers'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='absOriPalm',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Absolute Orientation: Palm'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='annotation_idgloss',
            field=models.CharField(help_text="\n    This is the Dutch name of a sign used by annotators when glossing the corpus in\nan ELAN annotation file. The Annotation Idgloss may be the same for two or\nmore entries (each with their own 'Sign Entry Name'). If two sign entries\nhave the same 'Annotation Idgloss' that means they differ in form in only\nminor or insignificant ways that can be ignored.", max_length=30, unique=True, verbose_name='Annotation ID Gloss: Dutch'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='annotation_idgloss_en',
            field=models.CharField(blank=True, help_text="\n    This is the English name of a sign used by annotators when glossing the corpus in\nan ELAN annotation file. The Annotation Idgloss may be the same for two or\nmore entries (each with their own 'Sign Entry Name'). If two sign entries\nhave the same 'Annotation Idgloss' that means they differ in form in only\nminor or insignificant ways that can be ignored.", max_length=30, unique=True, verbose_name='Annotation ID Gloss: English'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='contType',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('2', 'Brush'), ('6', 'Continuous'), ('8', 'Continuous > final'), ('13', 'Continuous > none'), ('12', 'Double'), ('4', 'Final'), ('5', 'Initial'), ('11', 'None > final'), ('9', 'None > initial')], max_length=5, null=True, verbose_name='Contact Type'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='derivHist',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('4', 'Arc'), ('37', 'Circle'), ('44', 'Motivated shape'), ('45', 'Spiral'), ('6', 'Straight'), ('12', 'Zigzag')], max_length=50, verbose_name='Derivation history'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='domFlex',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Dominant hand - Flexion'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='domSF',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Dominant hand - Selected Fingers'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='domhndsh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('89', '#A'), ('90', '#B'), ('162', '#B > #A'), ('91', '#B > #L'), ('92', '#B > #S'), ('157', '#B > middlefinger'), ('93', '#C'), ('161', '#C > #I'), ('94', '#D'), ('95', '#E'), ('96', '#F'), ('97', '#F > #L'), ('163', '#G'), ('164', '#G'), ('98', '#I'), ('110', '#I > #L'), ('158', '#I > #N'), ('100', '#I > #R'), ('99', '#I > #W'), ('108', '#I > 1'), ('109', '#I > N'), ('42', '#K'), ('101', '#L'), ('102', '#M'), ('103', '#M > #V'), ('104', '#N'), ('105', '#N > #E'), ('165', '#O'), ('107', '#O > #K'), ('148', '#P'), ('166', '#Q'), ('167', '#R'), ('156', '#S'), ('112', '#S > #I'), ('111', '#S > #W'), ('113', '#T'), ('141', '#T > #L'), ('150', '#T > #V'), ('160', '#V'), ('115', '#W'), ('168', '#Y'), ('159', '#Y > #R'), ('15', '1'), ('21', '1_curved'), ('37', '3'), ('35', '4'), ('3', '5'), ('149', '5 > #V'), ('30', '5m'), ('43', '5mx'), ('19', '5r'), ('49', '5rx'), ('48', '9'), ('117', '=1'), ('118', '=3'), ('119', '=3 > =0'), ('120', '=4'), ('121', '=4 > =0'), ('122', '=5'), ('123', '=9'), ('124', '=A'), ('143', '=A > =T'), ('126', '=Baby_O'), ('127', '=F'), ('128', '=L'), ('144', '=L > =O'), ('129', '=O'), ('130', '=T'), ('131', '=V'), ('133', '=W'), ('134', '=W > =Beak2'), ('24', 'A'), ('153', 'A > 5'), ('6', 'B'), ('138', 'B+1'), ('26', 'B_bent'), ('13', 'B_curved'), ('62', 'Baby_C'), ('38', 'Baby_O'), ('29', 'Baby_beak'), ('155', 'Baby_beak > A'), ('83', 'Baby_beak_open'), ('22', 'Beak'), ('17', 'Beak2'), ('85', 'Beak2_open'), ('152', 'Beak2_open_spread'), ('23', 'Beak2_spread'), ('84', 'Beak_open'), ('87', 'Beak_open_spread'), ('86', 'Beak_spread'), ('27', 'C'), ('145', 'C > I'), ('136', 'C2_closed'), ('75', 'C2_spread'), ('12', 'C_spread'), ('34', 'D'), ('39', 'F'), ('59', 'Horns'), ('25', 'I'), ('146', 'I > #L'), ('147', 'I > #N'), ('9', 'L'), ('52', 'L2'), ('40', 'M'), ('80', 'Middle finger'), ('4', 'Money'), ('14', 'N'), ('142', 'N > B'), ('32', 'O'), ('139', 'O > 5m'), ('135', 'Other'), ('18', 'Q'), ('47', 'R'), ('8', 'S'), ('28', 'T'), ('154', 'T_open'), ('5', 'V'), ('20', 'V_curved'), ('16', 'W'), ('7', 'Y')], max_length=5, null=True, verbose_name='Strong Hand'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='final_domhndsh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('89', '#A'), ('90', '#B'), ('162', '#B > #A'), ('91', '#B > #L'), ('92', '#B > #S'), ('157', '#B > middlefinger'), ('93', '#C'), ('161', '#C > #I'), ('94', '#D'), ('95', '#E'), ('96', '#F'), ('97', '#F > #L'), ('163', '#G'), ('164', '#G'), ('98', '#I'), ('110', '#I > #L'), ('158', '#I > #N'), ('100', '#I > #R'), ('99', '#I > #W'), ('108', '#I > 1'), ('109', '#I > N'), ('42', '#K'), ('101', '#L'), ('102', '#M'), ('103', '#M > #V'), ('104', '#N'), ('105', '#N > #E'), ('165', '#O'), ('107', '#O > #K'), ('148', '#P'), ('166', '#Q'), ('167', '#R'), ('156', '#S'), ('112', '#S > #I'), ('111', '#S > #W'), ('113', '#T'), ('141', '#T > #L'), ('150', '#T > #V'), ('160', '#V'), ('115', '#W'), ('168', '#Y'), ('159', '#Y > #R'), ('15', '1'), ('21', '1_curved'), ('37', '3'), ('35', '4'), ('3', '5'), ('149', '5 > #V'), ('30', '5m'), ('43', '5mx'), ('19', '5r'), ('49', '5rx'), ('48', '9'), ('117', '=1'), ('118', '=3'), ('119', '=3 > =0'), ('120', '=4'), ('121', '=4 > =0'), ('122', '=5'), ('123', '=9'), ('124', '=A'), ('143', '=A > =T'), ('126', '=Baby_O'), ('127', '=F'), ('128', '=L'), ('144', '=L > =O'), ('129', '=O'), ('130', '=T'), ('131', '=V'), ('133', '=W'), ('134', '=W > =Beak2'), ('24', 'A'), ('153', 'A > 5'), ('6', 'B'), ('138', 'B+1'), ('26', 'B_bent'), ('13', 'B_curved'), ('62', 'Baby_C'), ('38', 'Baby_O'), ('29', 'Baby_beak'), ('155', 'Baby_beak > A'), ('83', 'Baby_beak_open'), ('22', 'Beak'), ('17', 'Beak2'), ('85', 'Beak2_open'), ('152', 'Beak2_open_spread'), ('23', 'Beak2_spread'), ('84', 'Beak_open'), ('87', 'Beak_open_spread'), ('86', 'Beak_spread'), ('27', 'C'), ('145', 'C > I'), ('136', 'C2_closed'), ('75', 'C2_spread'), ('12', 'C_spread'), ('34', 'D'), ('39', 'F'), ('59', 'Horns'), ('25', 'I'), ('146', 'I > #L'), ('147', 'I > #N'), ('9', 'L'), ('52', 'L2'), ('40', 'M'), ('80', 'Middle finger'), ('4', 'Money'), ('14', 'N'), ('142', 'N > B'), ('32', 'O'), ('139', 'O > 5m'), ('135', 'Other'), ('18', 'Q'), ('47', 'R'), ('8', 'S'), ('28', 'T'), ('154', 'T_open'), ('5', 'V'), ('20', 'V_curved'), ('16', 'W'), ('7', 'Y')], max_length=5, null=True, verbose_name='Final Dominant Handshape'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='final_loc',
            field=models.IntegerField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('21', 'Arm'), ('83', 'Back'), ('37', 'Back of head'), ('26', 'Belly'), ('14', 'Belly + forehead'), ('23', 'Cheek'), ('108', 'Cheek > chin'), ('72', 'Cheek contra'), ('16', 'Cheekbone'), ('8', 'Chest'), ('35', 'Chest > trunk'), ('74', 'Chest contra'), ('12', 'Chin'), ('70', 'Chin > chest'), ('28', 'Chin > neutral space'), ('102', 'Chin > weak hand: index finger'), ('33', 'Chin > weak hand: palm'), ('117', 'Chin > weak hand: thumb side'), ('18', 'Ear'), ('84', 'Ear > cheek'), ('77', 'Elbow'), ('15', 'Eye'), ('120', 'Eye > neutral space'), ('17', 'Face'), ('110', 'Face > head'), ('93', 'Flank'), ('7', 'Forehead'), ('34', 'Forehead > chest'), ('31', 'Forehead > chin'), ('106', 'Forehead > neutral space'), ('104', 'Forehead > weak hand: palm'), ('64', 'Forehead contra'), ('10', 'Head'), ('119', 'Head + neutral space'), ('113', 'Head > chest'), ('69', 'Head > neutral space'), ('32', 'Head > shoulder'), ('107', 'Head > weak hand: palm'), ('30', 'Head ipsi'), ('94', 'Hip'), ('92', 'Horizontal plane'), ('85', 'Knee'), ('45', 'Leg'), ('95', 'Lower arm'), ('19', 'Mouth'), ('114', 'Mouth > cheek'), ('48', 'Mouth > chest'), ('13', 'Mouth > chin'), ('58', 'Mouth > weak hand'), ('112', 'Mouth > weak hand: palm'), ('9', 'Neck'), ('52', 'Neck > chest'), ('75', 'Neck contra'), ('3', 'Neutral space'), ('2', 'Neutral space > head'), ('121', 'Neutral space > nose'), ('29', 'Neutral space/weak hand: front'), ('22', 'Nose'), ('103', 'Nose > chin'), ('122', 'Nose > neutral space'), ('116', 'Parallel plane'), ('4', 'Shoulder'), ('115', 'Shoulder > shoulder'), ('123', 'Shoulder > weak hand: palm'), ('55', 'Shoulder contra'), ('86', 'Shoulder contra > shoulder ipsi'), ('43', 'Temple'), ('78', 'Temple > chest'), ('79', 'Thumb'), ('27', 'Tongue'), ('97', 'Trunk'), ('54', 'Upper arm'), ('63', 'Upper lip'), ('118', 'Variable'), ('91', 'Virtual object'), ('5', 'Weak hand'), ('6', 'Weak hand > arm'), ('11', 'Weak hand: back'), ('109', 'Weak hand: base'), ('66', 'Weak hand: finger tips'), ('90', 'Weak hand: front'), ('96', 'Weak hand: index finger'), ('98', 'Weak hand: middle finger'), ('36', 'Weak hand: palm'), ('88', 'Weak hand: pinkie'), ('101', 'Weak hand: pinkie side'), ('99', 'Weak hand: ring finger'), ('59', 'Weak hand: thumb'), ('100', 'Weak hand: thumb side'), ('111', 'Weak hand: thumb side > arm'), ('89', 'Weak hand: web space'), ('50', 'Wrist')], null=True, verbose_name='Final Primary Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='final_secondary_loc',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('21', 'Arm'), ('83', 'Back'), ('37', 'Back of head'), ('26', 'Belly'), ('14', 'Belly + forehead'), ('23', 'Cheek'), ('108', 'Cheek > chin'), ('72', 'Cheek contra'), ('16', 'Cheekbone'), ('8', 'Chest'), ('35', 'Chest > trunk'), ('74', 'Chest contra'), ('12', 'Chin'), ('70', 'Chin > chest'), ('28', 'Chin > neutral space'), ('102', 'Chin > weak hand: index finger'), ('33', 'Chin > weak hand: palm'), ('117', 'Chin > weak hand: thumb side'), ('18', 'Ear'), ('84', 'Ear > cheek'), ('77', 'Elbow'), ('15', 'Eye'), ('120', 'Eye > neutral space'), ('17', 'Face'), ('110', 'Face > head'), ('93', 'Flank'), ('7', 'Forehead'), ('34', 'Forehead > chest'), ('31', 'Forehead > chin'), ('106', 'Forehead > neutral space'), ('104', 'Forehead > weak hand: palm'), ('64', 'Forehead contra'), ('10', 'Head'), ('119', 'Head + neutral space'), ('113', 'Head > chest'), ('69', 'Head > neutral space'), ('32', 'Head > shoulder'), ('107', 'Head > weak hand: palm'), ('30', 'Head ipsi'), ('94', 'Hip'), ('92', 'Horizontal plane'), ('85', 'Knee'), ('45', 'Leg'), ('95', 'Lower arm'), ('19', 'Mouth'), ('114', 'Mouth > cheek'), ('48', 'Mouth > chest'), ('13', 'Mouth > chin'), ('58', 'Mouth > weak hand'), ('112', 'Mouth > weak hand: palm'), ('9', 'Neck'), ('52', 'Neck > chest'), ('75', 'Neck contra'), ('3', 'Neutral space'), ('2', 'Neutral space > head'), ('121', 'Neutral space > nose'), ('29', 'Neutral space/weak hand: front'), ('22', 'Nose'), ('103', 'Nose > chin'), ('122', 'Nose > neutral space'), ('116', 'Parallel plane'), ('4', 'Shoulder'), ('115', 'Shoulder > shoulder'), ('123', 'Shoulder > weak hand: palm'), ('55', 'Shoulder contra'), ('86', 'Shoulder contra > shoulder ipsi'), ('43', 'Temple'), ('78', 'Temple > chest'), ('79', 'Thumb'), ('27', 'Tongue'), ('97', 'Trunk'), ('54', 'Upper arm'), ('63', 'Upper lip'), ('118', 'Variable'), ('91', 'Virtual object'), ('5', 'Weak hand'), ('6', 'Weak hand > arm'), ('11', 'Weak hand: back'), ('109', 'Weak hand: base'), ('66', 'Weak hand: finger tips'), ('90', 'Weak hand: front'), ('96', 'Weak hand: index finger'), ('98', 'Weak hand: middle finger'), ('36', 'Weak hand: palm'), ('88', 'Weak hand: pinkie'), ('101', 'Weak hand: pinkie side'), ('99', 'Weak hand: ring finger'), ('59', 'Weak hand: thumb'), ('100', 'Weak hand: thumb side'), ('111', 'Weak hand: thumb side > arm'), ('89', 'Weak hand: web space'), ('50', 'Wrist')], max_length=20, null=True, verbose_name='Final Subordinate Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='final_subhndsh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('89', '#A'), ('90', '#B'), ('162', '#B > #A'), ('91', '#B > #L'), ('92', '#B > #S'), ('157', '#B > middlefinger'), ('93', '#C'), ('161', '#C > #I'), ('94', '#D'), ('95', '#E'), ('96', '#F'), ('97', '#F > #L'), ('163', '#G'), ('164', '#G'), ('98', '#I'), ('110', '#I > #L'), ('158', '#I > #N'), ('100', '#I > #R'), ('99', '#I > #W'), ('108', '#I > 1'), ('109', '#I > N'), ('42', '#K'), ('101', '#L'), ('102', '#M'), ('103', '#M > #V'), ('104', '#N'), ('105', '#N > #E'), ('165', '#O'), ('107', '#O > #K'), ('148', '#P'), ('166', '#Q'), ('167', '#R'), ('156', '#S'), ('112', '#S > #I'), ('111', '#S > #W'), ('113', '#T'), ('141', '#T > #L'), ('150', '#T > #V'), ('160', '#V'), ('115', '#W'), ('168', '#Y'), ('159', '#Y > #R'), ('15', '1'), ('21', '1_curved'), ('37', '3'), ('35', '4'), ('3', '5'), ('149', '5 > #V'), ('30', '5m'), ('43', '5mx'), ('19', '5r'), ('49', '5rx'), ('48', '9'), ('117', '=1'), ('118', '=3'), ('119', '=3 > =0'), ('120', '=4'), ('121', '=4 > =0'), ('122', '=5'), ('123', '=9'), ('124', '=A'), ('143', '=A > =T'), ('126', '=Baby_O'), ('127', '=F'), ('128', '=L'), ('144', '=L > =O'), ('129', '=O'), ('130', '=T'), ('131', '=V'), ('133', '=W'), ('134', '=W > =Beak2'), ('24', 'A'), ('153', 'A > 5'), ('6', 'B'), ('138', 'B+1'), ('26', 'B_bent'), ('13', 'B_curved'), ('62', 'Baby_C'), ('38', 'Baby_O'), ('29', 'Baby_beak'), ('155', 'Baby_beak > A'), ('83', 'Baby_beak_open'), ('22', 'Beak'), ('17', 'Beak2'), ('85', 'Beak2_open'), ('152', 'Beak2_open_spread'), ('23', 'Beak2_spread'), ('84', 'Beak_open'), ('87', 'Beak_open_spread'), ('86', 'Beak_spread'), ('27', 'C'), ('145', 'C > I'), ('136', 'C2_closed'), ('75', 'C2_spread'), ('12', 'C_spread'), ('34', 'D'), ('39', 'F'), ('59', 'Horns'), ('25', 'I'), ('146', 'I > #L'), ('147', 'I > #N'), ('9', 'L'), ('52', 'L2'), ('40', 'M'), ('80', 'Middle finger'), ('4', 'Money'), ('14', 'N'), ('142', 'N > B'), ('32', 'O'), ('139', 'O > 5m'), ('135', 'Other'), ('18', 'Q'), ('47', 'R'), ('8', 'S'), ('28', 'T'), ('154', 'T_open'), ('5', 'V'), ('20', 'V_curved'), ('16', 'W'), ('7', 'Y')], max_length=5, null=True, verbose_name='Final Subordinate Handshape'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='handCh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('7', 'Bending'), ('6', 'Closing'), ('44', 'Closing + wiggling'), ('32', 'Closing > opening'), ('8', 'Curving'), ('5', 'Opening'), ('45', 'Opening + rubbing'), ('47', 'Opening + wiggling'), ('38', 'Opening > closing'), ('39', 'Rubbing'), ('21', 'Spreading'), ('46', 'Uncurving'), ('10', 'Unspreading'), ('42', 'Wiggling')], max_length=5, null=True, verbose_name='Handshape Change'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='handedness',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('2', '1'), ('4', '2a'), ('5', '2s'), ('6', 'X')], max_length=5, null=True, verbose_name='Handedness'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='iconType',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Type of iconicity'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='idgloss',
            field=models.CharField(help_text='\n    This is the unique identifying name of an entry of a sign form in the\ndatabase. No two Sign Entry Names can be exactly the same, but a "Sign\nEntry Name" can be (and often is) the same as the Annotation Idgloss.', max_length=50, verbose_name='Lemma ID Gloss'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='initial_secondary_loc',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('21', 'Arm'), ('83', 'Back'), ('37', 'Back of head'), ('26', 'Belly'), ('14', 'Belly + forehead'), ('23', 'Cheek'), ('108', 'Cheek > chin'), ('72', 'Cheek contra'), ('16', 'Cheekbone'), ('8', 'Chest'), ('35', 'Chest > trunk'), ('74', 'Chest contra'), ('12', 'Chin'), ('70', 'Chin > chest'), ('28', 'Chin > neutral space'), ('102', 'Chin > weak hand: index finger'), ('33', 'Chin > weak hand: palm'), ('117', 'Chin > weak hand: thumb side'), ('18', 'Ear'), ('84', 'Ear > cheek'), ('77', 'Elbow'), ('15', 'Eye'), ('120', 'Eye > neutral space'), ('17', 'Face'), ('110', 'Face > head'), ('93', 'Flank'), ('7', 'Forehead'), ('34', 'Forehead > chest'), ('31', 'Forehead > chin'), ('106', 'Forehead > neutral space'), ('104', 'Forehead > weak hand: palm'), ('64', 'Forehead contra'), ('10', 'Head'), ('119', 'Head + neutral space'), ('113', 'Head > chest'), ('69', 'Head > neutral space'), ('32', 'Head > shoulder'), ('107', 'Head > weak hand: palm'), ('30', 'Head ipsi'), ('94', 'Hip'), ('92', 'Horizontal plane'), ('85', 'Knee'), ('45', 'Leg'), ('95', 'Lower arm'), ('19', 'Mouth'), ('114', 'Mouth > cheek'), ('48', 'Mouth > chest'), ('13', 'Mouth > chin'), ('58', 'Mouth > weak hand'), ('112', 'Mouth > weak hand: palm'), ('9', 'Neck'), ('52', 'Neck > chest'), ('75', 'Neck contra'), ('3', 'Neutral space'), ('2', 'Neutral space > head'), ('121', 'Neutral space > nose'), ('29', 'Neutral space/weak hand: front'), ('22', 'Nose'), ('103', 'Nose > chin'), ('122', 'Nose > neutral space'), ('116', 'Parallel plane'), ('4', 'Shoulder'), ('115', 'Shoulder > shoulder'), ('123', 'Shoulder > weak hand: palm'), ('55', 'Shoulder contra'), ('86', 'Shoulder contra > shoulder ipsi'), ('43', 'Temple'), ('78', 'Temple > chest'), ('79', 'Thumb'), ('27', 'Tongue'), ('97', 'Trunk'), ('54', 'Upper arm'), ('63', 'Upper lip'), ('118', 'Variable'), ('91', 'Virtual object'), ('5', 'Weak hand'), ('6', 'Weak hand > arm'), ('11', 'Weak hand: back'), ('109', 'Weak hand: base'), ('66', 'Weak hand: finger tips'), ('90', 'Weak hand: front'), ('96', 'Weak hand: index finger'), ('98', 'Weak hand: middle finger'), ('36', 'Weak hand: palm'), ('88', 'Weak hand: pinkie'), ('101', 'Weak hand: pinkie side'), ('99', 'Weak hand: ring finger'), ('59', 'Weak hand: thumb'), ('100', 'Weak hand: thumb side'), ('111', 'Weak hand: thumb side > arm'), ('89', 'Weak hand: web space'), ('50', 'Wrist')], max_length=20, null=True, verbose_name='Initial Subordinate Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='locPrimLH',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('21', 'Arm'), ('83', 'Back'), ('37', 'Back of head'), ('26', 'Belly'), ('14', 'Belly + forehead'), ('23', 'Cheek'), ('108', 'Cheek > chin'), ('72', 'Cheek contra'), ('16', 'Cheekbone'), ('8', 'Chest'), ('35', 'Chest > trunk'), ('74', 'Chest contra'), ('12', 'Chin'), ('70', 'Chin > chest'), ('28', 'Chin > neutral space'), ('102', 'Chin > weak hand: index finger'), ('33', 'Chin > weak hand: palm'), ('117', 'Chin > weak hand: thumb side'), ('18', 'Ear'), ('84', 'Ear > cheek'), ('77', 'Elbow'), ('15', 'Eye'), ('120', 'Eye > neutral space'), ('17', 'Face'), ('110', 'Face > head'), ('93', 'Flank'), ('7', 'Forehead'), ('34', 'Forehead > chest'), ('31', 'Forehead > chin'), ('106', 'Forehead > neutral space'), ('104', 'Forehead > weak hand: palm'), ('64', 'Forehead contra'), ('10', 'Head'), ('119', 'Head + neutral space'), ('113', 'Head > chest'), ('69', 'Head > neutral space'), ('32', 'Head > shoulder'), ('107', 'Head > weak hand: palm'), ('30', 'Head ipsi'), ('94', 'Hip'), ('92', 'Horizontal plane'), ('85', 'Knee'), ('45', 'Leg'), ('95', 'Lower arm'), ('19', 'Mouth'), ('114', 'Mouth > cheek'), ('48', 'Mouth > chest'), ('13', 'Mouth > chin'), ('58', 'Mouth > weak hand'), ('112', 'Mouth > weak hand: palm'), ('9', 'Neck'), ('52', 'Neck > chest'), ('75', 'Neck contra'), ('3', 'Neutral space'), ('2', 'Neutral space > head'), ('121', 'Neutral space > nose'), ('29', 'Neutral space/weak hand: front'), ('22', 'Nose'), ('103', 'Nose > chin'), ('122', 'Nose > neutral space'), ('116', 'Parallel plane'), ('4', 'Shoulder'), ('115', 'Shoulder > shoulder'), ('123', 'Shoulder > weak hand: palm'), ('55', 'Shoulder contra'), ('86', 'Shoulder contra > shoulder ipsi'), ('43', 'Temple'), ('78', 'Temple > chest'), ('79', 'Thumb'), ('27', 'Tongue'), ('97', 'Trunk'), ('54', 'Upper arm'), ('63', 'Upper lip'), ('118', 'Variable'), ('91', 'Virtual object'), ('5', 'Weak hand'), ('6', 'Weak hand > arm'), ('11', 'Weak hand: back'), ('109', 'Weak hand: base'), ('66', 'Weak hand: finger tips'), ('90', 'Weak hand: front'), ('96', 'Weak hand: index finger'), ('98', 'Weak hand: middle finger'), ('36', 'Weak hand: palm'), ('88', 'Weak hand: pinkie'), ('101', 'Weak hand: pinkie side'), ('99', 'Weak hand: ring finger'), ('59', 'Weak hand: thumb'), ('100', 'Weak hand: thumb side'), ('111', 'Weak hand: thumb side > arm'), ('89', 'Weak hand: web space'), ('50', 'Wrist')], max_length=5, null=True, verbose_name='Placement Active Articulator LH'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='locprim',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('21', 'Arm'), ('83', 'Back'), ('37', 'Back of head'), ('26', 'Belly'), ('14', 'Belly + forehead'), ('23', 'Cheek'), ('108', 'Cheek > chin'), ('72', 'Cheek contra'), ('16', 'Cheekbone'), ('8', 'Chest'), ('35', 'Chest > trunk'), ('74', 'Chest contra'), ('12', 'Chin'), ('70', 'Chin > chest'), ('28', 'Chin > neutral space'), ('102', 'Chin > weak hand: index finger'), ('33', 'Chin > weak hand: palm'), ('117', 'Chin > weak hand: thumb side'), ('18', 'Ear'), ('84', 'Ear > cheek'), ('77', 'Elbow'), ('15', 'Eye'), ('120', 'Eye > neutral space'), ('17', 'Face'), ('110', 'Face > head'), ('93', 'Flank'), ('7', 'Forehead'), ('34', 'Forehead > chest'), ('31', 'Forehead > chin'), ('106', 'Forehead > neutral space'), ('104', 'Forehead > weak hand: palm'), ('64', 'Forehead contra'), ('10', 'Head'), ('119', 'Head + neutral space'), ('113', 'Head > chest'), ('69', 'Head > neutral space'), ('32', 'Head > shoulder'), ('107', 'Head > weak hand: palm'), ('30', 'Head ipsi'), ('94', 'Hip'), ('92', 'Horizontal plane'), ('85', 'Knee'), ('45', 'Leg'), ('95', 'Lower arm'), ('19', 'Mouth'), ('114', 'Mouth > cheek'), ('48', 'Mouth > chest'), ('13', 'Mouth > chin'), ('58', 'Mouth > weak hand'), ('112', 'Mouth > weak hand: palm'), ('9', 'Neck'), ('52', 'Neck > chest'), ('75', 'Neck contra'), ('3', 'Neutral space'), ('2', 'Neutral space > head'), ('121', 'Neutral space > nose'), ('29', 'Neutral space/weak hand: front'), ('22', 'Nose'), ('103', 'Nose > chin'), ('122', 'Nose > neutral space'), ('116', 'Parallel plane'), ('4', 'Shoulder'), ('115', 'Shoulder > shoulder'), ('123', 'Shoulder > weak hand: palm'), ('55', 'Shoulder contra'), ('86', 'Shoulder contra > shoulder ipsi'), ('43', 'Temple'), ('78', 'Temple > chest'), ('79', 'Thumb'), ('27', 'Tongue'), ('97', 'Trunk'), ('54', 'Upper arm'), ('63', 'Upper lip'), ('118', 'Variable'), ('91', 'Virtual object'), ('5', 'Weak hand'), ('6', 'Weak hand > arm'), ('11', 'Weak hand: back'), ('109', 'Weak hand: base'), ('66', 'Weak hand: finger tips'), ('90', 'Weak hand: front'), ('96', 'Weak hand: index finger'), ('98', 'Weak hand: middle finger'), ('36', 'Weak hand: palm'), ('88', 'Weak hand: pinkie'), ('101', 'Weak hand: pinkie side'), ('99', 'Weak hand: ring finger'), ('59', 'Weak hand: thumb'), ('100', 'Weak hand: thumb side'), ('111', 'Weak hand: thumb side > arm'), ('89', 'Weak hand: web space'), ('50', 'Wrist')], max_length=20, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='locsecond',
            field=models.IntegerField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('21', 'Arm'), ('83', 'Back'), ('37', 'Back of head'), ('26', 'Belly'), ('14', 'Belly + forehead'), ('23', 'Cheek'), ('108', 'Cheek > chin'), ('72', 'Cheek contra'), ('16', 'Cheekbone'), ('8', 'Chest'), ('35', 'Chest > trunk'), ('74', 'Chest contra'), ('12', 'Chin'), ('70', 'Chin > chest'), ('28', 'Chin > neutral space'), ('102', 'Chin > weak hand: index finger'), ('33', 'Chin > weak hand: palm'), ('117', 'Chin > weak hand: thumb side'), ('18', 'Ear'), ('84', 'Ear > cheek'), ('77', 'Elbow'), ('15', 'Eye'), ('120', 'Eye > neutral space'), ('17', 'Face'), ('110', 'Face > head'), ('93', 'Flank'), ('7', 'Forehead'), ('34', 'Forehead > chest'), ('31', 'Forehead > chin'), ('106', 'Forehead > neutral space'), ('104', 'Forehead > weak hand: palm'), ('64', 'Forehead contra'), ('10', 'Head'), ('119', 'Head + neutral space'), ('113', 'Head > chest'), ('69', 'Head > neutral space'), ('32', 'Head > shoulder'), ('107', 'Head > weak hand: palm'), ('30', 'Head ipsi'), ('94', 'Hip'), ('92', 'Horizontal plane'), ('85', 'Knee'), ('45', 'Leg'), ('95', 'Lower arm'), ('19', 'Mouth'), ('114', 'Mouth > cheek'), ('48', 'Mouth > chest'), ('13', 'Mouth > chin'), ('58', 'Mouth > weak hand'), ('112', 'Mouth > weak hand: palm'), ('9', 'Neck'), ('52', 'Neck > chest'), ('75', 'Neck contra'), ('3', 'Neutral space'), ('2', 'Neutral space > head'), ('121', 'Neutral space > nose'), ('29', 'Neutral space/weak hand: front'), ('22', 'Nose'), ('103', 'Nose > chin'), ('122', 'Nose > neutral space'), ('116', 'Parallel plane'), ('4', 'Shoulder'), ('115', 'Shoulder > shoulder'), ('123', 'Shoulder > weak hand: palm'), ('55', 'Shoulder contra'), ('86', 'Shoulder contra > shoulder ipsi'), ('43', 'Temple'), ('78', 'Temple > chest'), ('79', 'Thumb'), ('27', 'Tongue'), ('97', 'Trunk'), ('54', 'Upper arm'), ('63', 'Upper lip'), ('118', 'Variable'), ('91', 'Virtual object'), ('5', 'Weak hand'), ('6', 'Weak hand > arm'), ('11', 'Weak hand: back'), ('109', 'Weak hand: base'), ('66', 'Weak hand: finger tips'), ('90', 'Weak hand: front'), ('96', 'Weak hand: index finger'), ('98', 'Weak hand: middle finger'), ('36', 'Weak hand: palm'), ('88', 'Weak hand: pinkie'), ('101', 'Weak hand: pinkie side'), ('99', 'Weak hand: ring finger'), ('59', 'Weak hand: thumb'), ('100', 'Weak hand: thumb side'), ('111', 'Weak hand: thumb side > arm'), ('89', 'Weak hand: web space'), ('50', 'Wrist')], null=True, verbose_name='Secondary Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='movDir',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('5', 'Backwards'), ('87', 'Backwards + downwards'), ('93', 'Backwards + ipsilateral'), ('72', 'Backwards + upwards'), ('6', 'Backwards > downwards'), ('15', 'Backwards/forwards'), ('50', 'Contralateral'), ('53', 'Contralateral + downwards'), ('54', 'Contralateral + forwards'), ('52', 'Contralateral + upwards'), ('3', 'Contralateral > forwards'), ('98', 'Distal'), ('8', 'Downwards'), ('56', 'Downwards + forwards'), ('57', 'Downwards + ipsilateral'), ('58', 'Downwards + ipsilateral > downwards'), ('94', 'Downwards + towards'), ('59', 'Downwards > contralateral'), ('4', 'Downwards > forwards'), ('55', 'Downwards > ipsilateral'), ('69', 'Downwards/upwards'), ('90', 'Downwards/upwards + ipsilateral'), ('16', 'Forwards'), ('60', 'Forwards + ipsilateral'), ('61', 'Forwards + upwards'), ('63', 'Forwards > contralateral'), ('17', 'Forwards > downwards'), ('62', 'Forwards > ipsilateral'), ('64', 'Forwards > ipsilateral > forwards'), ('92', 'Forwards > upwards'), ('51', 'Ipsilateral'), ('91', 'Ipsilateral + up and down'), ('65', 'Ipsilateral + upwards'), ('71', 'Ipsilateral > contralateral'), ('68', 'Ipsilateral > downwards'), ('66', 'Ipsilateral > downwards > contralateral'), ('67', 'Ipsilateral > upwards'), ('89', 'Ipsilateral and contralateral'), ('88', 'Ipsilateral/contralateral'), ('95', 'Proximal'), ('46', 'To and fro'), ('96', 'Towards location'), ('70', 'Up and down'), ('32', 'Upwards'), ('33', 'Upwards > downwards'), ('73', 'Upwards > forwards > downwards'), ('49', 'Variable')], max_length=5, null=True, verbose_name='Movement Direction'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='movMan',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Movement Manner'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='movSh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('4', 'Arc'), ('37', 'Circle'), ('44', 'Motivated shape'), ('45', 'Spiral'), ('6', 'Straight'), ('12', 'Zigzag')], max_length=5, null=True, verbose_name='Movement Shape'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='namEnt',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('6', 'Brand'), ('17', 'Company'), ('15', 'Continent'), ('7', 'Country'), ('8', 'Device'), ('19', 'Drink'), ('12', 'Event'), ('20', 'Magazine'), ('13', 'Newspaper'), ('16', 'Organisation'), ('2', 'Person'), ('4', 'Place'), ('11', 'Place nickname'), ('9', 'Product'), ('10', 'Project'), ('3', 'Public figure'), ('5', 'Region'), ('14', 'Story character'), ('18', 'Team')], max_length=5, null=True, verbose_name='Named Entity'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='oriCh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('3', 'Extension'), ('13', 'Extension > flexion'), ('14', 'Extension/flexion'), ('4', 'Flexion'), ('8', 'Pronation'), ('9', 'Pronation/supination'), ('12', 'Radial and ulnar flexion'), ('5', 'Radial flexion'), ('2', 'Rotation'), ('7', 'Supination'), ('6', 'Ulnar flexion')], max_length=5, null=True, verbose_name='Orientation Change'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='relOriLoc',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('8', 'Back'), ('27', 'Back/palm'), ('28', 'Back/palm > palm'), ('3', 'Base'), ('4', 'Finger tips'), ('24', 'Finger tips/base'), ('26', 'Fingerspelling'), ('25', 'Front'), ('7', 'Palm'), ('5', 'Radial'), ('2', 'Radial/ulnar'), ('6', 'Ulnar')], max_length=5, null=True, verbose_name='Relative Orientation: Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='relOriMov',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('7', 'Back'), ('25', 'Back + base'), ('31', 'Back + ulnar'), ('46', 'Back > finger tips'), ('45', 'Back > front'), ('15', 'Back > palm'), ('38', 'Back/base'), ('48', 'Back/finger tips'), ('23', 'Back/palm'), ('22', 'Base'), ('24', 'Base + front'), ('26', 'Base + palm'), ('27', 'Base + ulnar'), ('28', 'Base > base'), ('39', 'Base > front'), ('37', 'Base > palm'), ('29', 'Base > ulnar'), ('36', 'Base/front'), ('4', 'Finger tips'), ('44', 'Finger tips > base'), ('43', 'Finger tips > palm'), ('35', 'Finger tips/base'), ('6', 'Front'), ('10', 'Front + ulnar'), ('3', 'Palm'), ('49', 'Palm + radial'), ('40', 'Palm + ulnar'), ('33', 'Palm > back'), ('30', 'Palm > base'), ('5', 'Radial'), ('34', 'Radial > ulnar'), ('32', 'Radial/ulnar'), ('2', 'Ulnar'), ('47', 'Ulnar > base'), ('41', 'Ulnar > base > radial'), ('42', 'Ulnar > front'), ('17', 'Ulnar > palm'), ('19', 'Ulnar > palm > radial'), ('9', 'Variable')], max_length=5, null=True, verbose_name='Relative Orientation: Movement'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='relatArtic',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('45', 'Above'), ('47', 'Above/below'), ('43', 'Back'), ('46', 'Below'), ('39', 'Contact'), ('41', 'Cross'), ('42', 'Front'), ('44', 'Front/back'), ('48', 'Inside'), ('27', 'Interlocked'), ('40', 'Interwoven')], max_length=5, null=True, verbose_name='Relation between Articulators'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='semField',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('4', 'Animal'), ('5', 'Arithmetic'), ('6', 'Arts'), ('7', 'Body part'), ('8', 'Car'), ('10', 'City'), ('11', 'Clothing'), ('12', 'Colour'), ('9', 'Cooking'), ('2', 'Day'), ('3', 'Deaf'), ('13', 'Drink'), ('14', 'Education'), ('15', 'Family'), ('17', 'Food'), ('18', 'Furniture'), ('19', 'Government'), ('21', 'Health'), ('23', 'Language act'), ('24', 'Law'), ('50', 'Linguistics'), ('25', 'Material'), ('26', 'Metalinguistic'), ('27', 'Mind'), ('28', 'Money'), ('29', 'Nature'), ('30', 'Number'), ('31', 'People'), ('32', 'Physical act'), ('33', 'Quality'), ('34', 'Quantity'), ('35', 'Question'), ('36', 'Recreation'), ('37', 'Salutation'), ('38', 'Sensation'), ('39', 'Sexuality'), ('40', 'Shapes'), ('41', 'Shopping'), ('49', 'Space'), ('42', 'Sport'), ('43', 'Technology'), ('44', 'Time'), ('45', 'Travel'), ('46', 'Utensil'), ('47', 'Weather'), ('48', 'Work')], max_length=5, null=True, verbose_name='Semantic Field'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='sense',
            field=models.IntegerField(blank=True, help_text='If there is more than one sense of a sign enter a number here, all signs with sense>1 will use the same video as sense=1', null=True, verbose_name='Sense Number'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='sn',
            field=models.IntegerField(blank=True, help_text='Sign Number must be a unique integer and defines the ordering of signs in the dictionary', null=True, unique=True, verbose_name='Sign Number'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='subhndsh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('89', '#A'), ('90', '#B'), ('162', '#B > #A'), ('91', '#B > #L'), ('92', '#B > #S'), ('157', '#B > middlefinger'), ('93', '#C'), ('161', '#C > #I'), ('94', '#D'), ('95', '#E'), ('96', '#F'), ('97', '#F > #L'), ('163', '#G'), ('164', '#G'), ('98', '#I'), ('110', '#I > #L'), ('158', '#I > #N'), ('100', '#I > #R'), ('99', '#I > #W'), ('108', '#I > 1'), ('109', '#I > N'), ('42', '#K'), ('101', '#L'), ('102', '#M'), ('103', '#M > #V'), ('104', '#N'), ('105', '#N > #E'), ('165', '#O'), ('107', '#O > #K'), ('148', '#P'), ('166', '#Q'), ('167', '#R'), ('156', '#S'), ('112', '#S > #I'), ('111', '#S > #W'), ('113', '#T'), ('141', '#T > #L'), ('150', '#T > #V'), ('160', '#V'), ('115', '#W'), ('168', '#Y'), ('159', '#Y > #R'), ('15', '1'), ('21', '1_curved'), ('37', '3'), ('35', '4'), ('3', '5'), ('149', '5 > #V'), ('30', '5m'), ('43', '5mx'), ('19', '5r'), ('49', '5rx'), ('48', '9'), ('117', '=1'), ('118', '=3'), ('119', '=3 > =0'), ('120', '=4'), ('121', '=4 > =0'), ('122', '=5'), ('123', '=9'), ('124', '=A'), ('143', '=A > =T'), ('126', '=Baby_O'), ('127', '=F'), ('128', '=L'), ('144', '=L > =O'), ('129', '=O'), ('130', '=T'), ('131', '=V'), ('133', '=W'), ('134', '=W > =Beak2'), ('24', 'A'), ('153', 'A > 5'), ('6', 'B'), ('138', 'B+1'), ('26', 'B_bent'), ('13', 'B_curved'), ('62', 'Baby_C'), ('38', 'Baby_O'), ('29', 'Baby_beak'), ('155', 'Baby_beak > A'), ('83', 'Baby_beak_open'), ('22', 'Beak'), ('17', 'Beak2'), ('85', 'Beak2_open'), ('152', 'Beak2_open_spread'), ('23', 'Beak2_spread'), ('84', 'Beak_open'), ('87', 'Beak_open_spread'), ('86', 'Beak_spread'), ('27', 'C'), ('145', 'C > I'), ('136', 'C2_closed'), ('75', 'C2_spread'), ('12', 'C_spread'), ('34', 'D'), ('39', 'F'), ('59', 'Horns'), ('25', 'I'), ('146', 'I > #L'), ('147', 'I > #N'), ('9', 'L'), ('52', 'L2'), ('40', 'M'), ('80', 'Middle finger'), ('4', 'Money'), ('14', 'N'), ('142', 'N > B'), ('32', 'O'), ('139', 'O > 5m'), ('135', 'Other'), ('18', 'Q'), ('47', 'R'), ('8', 'S'), ('28', 'T'), ('154', 'T_open'), ('5', 'V'), ('20', 'V_curved'), ('16', 'W'), ('7', 'Y')], max_length=5, null=True, verbose_name='Weak Hand'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='valence',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('4', 'Ditransitive'), ('2', 'Intransitive'), ('3', 'Transitive'), ('5', 'Transitive and intransitive')], max_length=50, null=True, verbose_name='Valence'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='wordClass',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('5', 'Adjective'), ('2', 'Noun'), ('4', 'Particle'), ('3', 'Verb')], max_length=5, null=True, verbose_name='Word class'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='wordClass2',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('5', 'Adjective'), ('2', 'Noun'), ('4', 'Particle'), ('3', 'Verb')], max_length=5, null=True, verbose_name='Word class 2'),
        ),
        migrations.AlterField(
            model_name='morpheme',
            name='mrpType',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('23', 'Abs. Ori'), ('13', 'Articulator: Aperture'), ('14', 'Articulator: Finger shape'), ('12', 'Articulator: NSF'), ('2', 'Articulator: SF'), ('15', 'Articulator: Spreading'), ('11', 'Hand arrangement: Arrangement'), ('10', 'Hand arrangement: Handedness'), ('27', 'Location: Contact type'), ('25', 'Location: Loc'), ('26', 'Location: Loc side'), ('28', 'Movement: Local'), ('31', 'Movement: Manner'), ('32', 'Movement: Path direction'), ('29', 'Movement: Path shape'), ('30', 'Movement: Repetition'), ('5', 'Rel. Ori')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='morphologydefinition',
            name='role',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A'), ('2', 'Compound part 1'), ('3', 'Compound part 2'), ('4', 'Compound part 3'), ('5', 'Compound part 4')], max_length=5),
        ),
        migrations.AlterField(
            model_name='othermedia',
            name='type',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A'), ('2', 'Alternative citation form'), ('3', 'Citation form with mouthing'), ('10', 'Handy signs: experiments (mouthing, long)'), ('5', 'Handy signs: experiments (mouthing, short)'), ('8', 'Handy signs: experiments (no mouthing, long)'), ('9', 'Handy signs: experiments (no mouthing, short)'), ('4', 'Sign in sentence context'), ('6', 'SignPhon: citation form'), ('7', 'SignPhon: sentence')], max_length=5),
        ),
        migrations.AlterField(
            model_name='relation',
            name='role',
            field=models.CharField(choices=[('homonym', 'Homonym'), ('synonym', 'Synonym'), ('variant', 'Variant'), ('antonym', 'Antonym'), ('hyponym', 'Hyponym'), ('hypernym', 'Hypernym'), ('seealso', 'See Also')], max_length=20),
        ),
        migrations.AlterField(
            model_name='relationtoforeignsign',
            name='loan',
            field=models.BooleanField(default=False, verbose_name='Loan Sign'),
        ),
        migrations.AlterField(
            model_name='relationtoforeignsign',
            name='other_lang',
            field=models.CharField(max_length=20, verbose_name='Related Language'),
        ),
        migrations.AlterField(
            model_name='relationtoforeignsign',
            name='other_lang_gloss',
            field=models.CharField(max_length=50, verbose_name='Gloss in related language'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='index',
            field=models.IntegerField(verbose_name='Index'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_used_language',
            field=models.CharField(default='en', max_length=5),
        ),
    ]
