# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_auto_20170517_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldchoice',
            name='chinese_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
