# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_auto_20170720_1217'),
    ]

    def insert_language(apps,schema_editor):
        Language = apps.get_model('dictionary','language')
        l = Language(name="English",name_en="English",language_code_2char="en",
                    language_code_3char="eng",description="Default English")
        l.save()

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_nl', models.CharField(max_length=50, null=True)),
                ('name_zh_hans', models.CharField(max_length=50, null=True)),
                ('language_code_2char', models.CharField(help_text='Language code (2 characters long) of a written language. This also includes codes of the form zh-Hans, cf. IETF BCP 47', max_length=7)),
                ('language_code_3char', models.CharField(help_text='ISO 639-3 language code (3 characters long) of a written language.', max_length=3)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(insert_language),
    ]

