# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import signbank.dictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_auto_20170802_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='language',
            field=models.ForeignKey(default=signbank.dictionary.models.get_default_language_id, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Language'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='contType',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('2', 'Brush'), ('6', 'Continuous'), ('8', 'Continuous > final'), ('13', 'Continuous > none'), ('12', 'Double'), ('4', 'Final'), ('14', 'Final > continuous'), ('5', 'Initial'), ('11', 'None > final'), ('9', 'None > initial')], max_length=5, null=True, verbose_name='Contact Type'),
        ),
    ]
