# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_auto_20170802_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('is_public', models.BooleanField(default=False, help_text='Is this dataset public or private?')),
                ('description', models.TextField()),
                ('signlanguage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.SignLanguage')),
            ],
            options={
                'permissions': (('view_dataset', 'View dataset'),),
            },
        ),
        migrations.AlterField(
            model_name='language',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together=set([('gloss', 'language', 'translation')]),
        ),
        migrations.AddField(
            model_name='dataset',
            name='translation_languages',
            field=models.ManyToManyField(help_text='These languages are shown as optionsfor translation equivalents.', to='dictionary.Language'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='dataset',
            field=models.ForeignKey(help_text='Dataset a gloss is part of', null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Dataset', verbose_name='Glosses dataset'),
        ),
    ]
