# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0011_auto_20170810_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handshape',
            fields=[
                ('machine_value', models.IntegerField(primary_key=True, serialize=False)),
                ('english_name', models.CharField(max_length=50)),
                ('dutch_name', models.CharField(max_length=50)),
                ('chinese_name', models.CharField(blank=True, max_length=50)),
                ('hsNumSel', models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Quantity')),
                ('hsFingSel', models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Finger selection')),
                ('hsFingSel2', models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Finger selection 2')),
                ('hsFingConf', models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Finger configuration')),
                ('hsFingConf2', models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Finger configuration 2')),
                ('hsAperture', models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Aperture')),
                ('hsThumb', models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Thumb')),
                ('hsSpread', models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Spreading')),
                ('hsFingUnsel', models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Unselected fingers')),
                ('fsT', models.NullBooleanField(default=False, verbose_name='T')),
                ('fsI', models.NullBooleanField(default=False, verbose_name='I')),
                ('fsM', models.NullBooleanField(default=False, verbose_name='M')),
                ('fsR', models.NullBooleanField(default=False, verbose_name='R')),
                ('fsP', models.NullBooleanField(default=False, verbose_name='P')),
                ('fs2T', models.NullBooleanField(default=False, verbose_name='T2')),
                ('fs2I', models.NullBooleanField(default=False, verbose_name='I2')),
                ('fs2M', models.NullBooleanField(default=False, verbose_name='M2')),
                ('fs2R', models.NullBooleanField(default=False, verbose_name='R2')),
                ('fs2P', models.NullBooleanField(default=False, verbose_name='P2')),
                ('ufT', models.NullBooleanField(default=False, verbose_name='Tu')),
                ('ufI', models.NullBooleanField(default=False, verbose_name='Iu')),
                ('ufM', models.NullBooleanField(default=False, verbose_name='Mu')),
                ('ufR', models.NullBooleanField(default=False, verbose_name='Ru')),
                ('ufP', models.NullBooleanField(default=False, verbose_name='Pu')),
            ],
        ),
    ]
