# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0012_auto_20170810_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='gloss',
            name='domhndsh_letter',
            field=models.NullBooleanField(verbose_name='letter'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='domhndsh_number',
            field=models.NullBooleanField(verbose_name='number'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='subhndsh_letter',
            field=models.NullBooleanField(verbose_name='letter'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='subhndsh_number',
            field=models.NullBooleanField(verbose_name='number'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='weakdrop',
            field=models.NullBooleanField(verbose_name='WD'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='weakprop',
            field=models.NullBooleanField(verbose_name='WP'),
        ),
    ]
