# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0013_auto_20170830_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='selected_datasets',
            field=models.ManyToManyField(to='dictionary.Dataset'),
        ),
    ]
