# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0015_auto_20171120_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationIdglossTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='\n        This is the name of a sign used by annotators when glossing the corpus in\n        an ELAN annotation file.', max_length=30, verbose_name='Annotation ID Gloss')),
            ],
        ),
        migrations.AddField(
            model_name='annotationidglosstranslation',
            name='gloss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Gloss'),
        ),
        migrations.AddField(
            model_name='annotationidglosstranslation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Language'),
        ),
        migrations.AlterUniqueTogether(
            name='annotationidglosstranslation',
            unique_together=set([('gloss', 'language')]),
        ),
    ]
