# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0018_auto_20171208_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gloss',
            name='annotation_idgloss',
        ),
        migrations.RemoveField(
            model_name='gloss',
            name='annotation_idgloss_en',
        ),
    ]
