# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 12:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0020_auto_20180228_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='acronym',
            field=models.CharField(blank=True, help_text='Abbreviation for the dataset', max_length=10),
        ),
        migrations.AddField(
            model_name='dataset',
            name='conditions_of_use',
            field=models.TextField(blank=True, help_text='Conditions of Use. Content license.This is different than the software code license.'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='copyright',
            field=models.TextField(blank=True, help_text='Copyright. Content license.This is different than the software code license.'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='owners',
            field=models.ManyToManyField(help_text='Users responsible for the dataset content.', to=settings.AUTH_USER_MODEL),
        ),
    ]
