# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0021_auto_20180328_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='LemmaIdgloss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.ForeignKey(help_text='Dataset a lemma is part of', null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Dataset', verbose_name='Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='LemmaIdglossTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The lemma translation text.', max_length=30, verbose_name='Lemma ID Gloss translation')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Language')),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.LemmaIdgloss')),
            ],
        ),
    ]
