# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0025_auto_20180801_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lemmaidgloss',
            options={'ordering': ['dataset__name']},
        ),
    ]
