# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 11:40
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0026_auto_20180802_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='default_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='datasets_with_default_language', to='dictionary.Language'),
        ),

    ]
