# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0027_auto_20180803_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='gloss',
            name='concConcSet',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Conception Concept Set'),
        )
    ]
