# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0028_auto_20181116_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='exclude_choices',
            field=models.ManyToManyField(help_text='Exclude these field choices', to='dictionary.FieldChoice'),
        )
    ]
