# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0032_auto_20190320_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='role',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Type'),
        ),
    ]
