# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-23 11:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0034_auto_20190410_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.CharField(blank=True, max_length=100)),
                ('new_value', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='glossrevision',
            name='gloss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Gloss'),
        ),
        migrations.AddField(
            model_name='glossrevision',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        )
    ]
