# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-16 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0035_auto_20190823_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('speakers_are_cross_referenced', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('creation_time', models.DateTimeField(blank=True)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Corpus')),
            ],
        ),
        migrations.CreateModel(
            name='GlossFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'm'), ('Female', 'f')], max_length=1)),
                ('age', models.IntegerField(blank=True)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='glossfrequency',
            name='gloss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Gloss'),
        ),
        migrations.AddField(
            model_name='glossfrequency',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Speaker'),
        ),
    ]
