# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-01 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0036_auto_20191016_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='handedness',
            field=models.CharField(blank=True, choices=[('Right', 'r'), ('Left', 'l'), ('Ambidextrous', 'a')], max_length=1),
        )
    ]
