# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-28 14:33

from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0037_auto_20191101_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldchoice',
            name='field_color',
            field=colorfield.fields.ColorField(default='ffffff', max_length=18),
        ),
    ]
