# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-29 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import signbank.dictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0037_auto_20191101_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='role_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='definition', to='dictionary.FieldChoice', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='absOriFing_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absolute_orientation_fingers', to='dictionary.FieldChoice', verbose_name='Absolute Orientation: Fingers'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='absOriPalm_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absolute_orientation_palm', to='dictionary.FieldChoice', verbose_name='Absolute Orientation: Palm'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='contType_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_type', to='dictionary.FieldChoice', verbose_name='Contact Type'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='derivHist_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivation_history', to='dictionary.FieldChoice', verbose_name='Derivation history'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='domFlex_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dominant_hand_flexion', to='dictionary.FieldChoice', verbose_name='Dominant hand - Flexion'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='domSF_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dominant_hand_selected_fingers', to='dictionary.FieldChoice', verbose_name='Dominant hand - Selected Fingers'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='domhndsh_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strong_hand', to='dictionary.FieldChoice', verbose_name='Strong Hand'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='final_domhndsh_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_dominant_handshape', to='dictionary.FieldChoice', verbose_name='Final Dominant Handshape'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='final_loc_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_primary_location', to='dictionary.FieldChoice', verbose_name='Final Primary Location'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='final_secondary_loc_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_subordinate_location', to='dictionary.FieldChoice', verbose_name='Final Subordinate Location'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='final_subhndsh_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_subordinate_handshape', to='dictionary.FieldChoice', verbose_name='Final Subordinate Handshape'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='handCh_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handshape_change', to='dictionary.FieldChoice', verbose_name='Handshape Change'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='handedness_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handedness', to='dictionary.FieldChoice', verbose_name='Handedness'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='iconType_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_of_iconicity', to='dictionary.FieldChoice', verbose_name='Type of iconicity'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='initial_secondary_loc_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_subordinate_location', to='dictionary.FieldChoice', verbose_name='Initial Subordinate Location'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='locPrimLH_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_active_articulator_lh', to='dictionary.FieldChoice', verbose_name='Placement Active Articulator LH'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='locprim_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='dictionary.FieldChoice', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='locsecond_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_location', to='dictionary.FieldChoice', verbose_name='Secondary Location'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='movDir_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_direction', to='dictionary.FieldChoice', verbose_name='Movement Direction'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='movMan_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_manner', to='dictionary.FieldChoice', verbose_name='Movement Manner'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='movSh_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_shape', to='dictionary.FieldChoice', verbose_name='Movement Shape'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='namEnt_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='named_entity', to='dictionary.FieldChoice', verbose_name='Named Entity'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='oriCh_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orientation_change', to='dictionary.FieldChoice', verbose_name='Orientation Change'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='relOriLoc_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relative_orientation_location', to='dictionary.FieldChoice', verbose_name='Relative Orientation: Location'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='relOriMov_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relative_orientation_movement', to='dictionary.FieldChoice', verbose_name='Relative Orientation: Movement'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='relatArtic_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relation_between_articulators', to='dictionary.FieldChoice', verbose_name='Relation between Articulators'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='semField_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semantic_field', to='dictionary.FieldChoice', verbose_name='Semantic Field'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='subhndsh_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weak_hand', to='dictionary.FieldChoice', verbose_name='Weak Hand'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='valence_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valence', to='dictionary.FieldChoice', verbose_name='Valence'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='wordClass2_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_class_2', to='dictionary.FieldChoice', verbose_name='Word class 2'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='wordClass_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_class', to='dictionary.FieldChoice', verbose_name='Word class'),
        ),
        migrations.AddField(
            model_name='handshape',
            name='hsAperture_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aperture', to='dictionary.FieldChoice', verbose_name='Aperture'),
        ),
        migrations.AddField(
            model_name='handshape',
            name='hsFingConf2_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finger_configuration_2', to='dictionary.FieldChoice', verbose_name='Finger configuration 2'),
        ),
        migrations.AddField(
            model_name='handshape',
            name='hsFingConf_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finger_configuration', to='dictionary.FieldChoice', verbose_name='Finger configuration'),
        ),
        migrations.AddField(
            model_name='handshape',
            name='hsFingSel2_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finger_selection_2', to='dictionary.FieldChoice', verbose_name='Finger selection 2'),
        ),
        migrations.AddField(
            model_name='handshape',
            name='hsFingSel_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finger_selection', to='dictionary.FieldChoice', verbose_name='Finger selection'),
        ),
        migrations.AddField(
            model_name='handshape',
            name='hsFingUnsel_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unselected_fingers', to='dictionary.FieldChoice', verbose_name='Unselected fingers'),
        ),
        migrations.AddField(
            model_name='handshape',
            name='hsNumSel_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quantity', to='dictionary.FieldChoice', verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='handshape',
            name='hsSpread_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spreading', to='dictionary.FieldChoice', verbose_name='Spreading'),
        ),
        migrations.AddField(
            model_name='handshape',
            name='hsThumb_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumb', to='dictionary.FieldChoice', verbose_name='Thumb'),
        ),
        migrations.AddField(
            model_name='morpheme',
            name='mrpType_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='morpheme_type', to='dictionary.FieldChoice', verbose_name='Has morpheme type'),
        ),
        migrations.AddField(
            model_name='othermedia',
            name='type_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_media', to='dictionary.FieldChoice', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='fieldchoice',
            name='field',
            field=models.CharField(choices=[('AbsOriFing', 'AbsOriFing'), ('AbsOriPalm', 'AbsOriPalm'), ('Aperture', 'Aperture'), ('Articulator WH: selected fingers', 'Articulator WH: selected fingers'), ('ContactType', 'ContactType'), ('derivHist', 'derivHist'), ('DominantHandFlexion', 'DominantHandFlexion'), ('DominantHandSelectedFingers', 'DominantHandSelectedFingers'), ('FingerSelection', 'FingerSelection'), ('Handedness', 'Handedness'), ('Handshape', 'Handshape'), ('iconicity', 'iconicity'), ('HandshapeChange', 'HandshapeChange'), ('JointConfiguration', 'JointConfiguration'), ('Location', 'Location'), ('MinorLocation', 'MinorLocation'), ('MorphemeType', 'MorphemeType'), ('MorphologyType', 'MorphologyType'), ('MovementDir', 'MovementDir'), ('MovementMan', 'MovementMan'), ('MovementShape', 'MovementShape'), ('NamedEntity', 'NamedEntity'), ('NoteType', 'NoteType'), ('OriChange', 'OriChange'), ('OtherMediaType', 'OtherMediaType'), ('PathOnPath', 'PathOnPath'), ('Quantity', 'Quantity'), ('RelOriLoc', 'RelOriLoc'), ('RelOriMov', 'RelOriMov'), ('RelatArtic', 'RelatArtic'), ('SemField', 'SemField'), ('Spreading', 'Spreading'), ('Thumb', 'Thumb'), ('Valence', 'Valence'), ('WordClass', 'WordClass')], max_length=50),
        ),
    ]
