# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-04-19 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0038_auto_20201028_1533'),
    ]

    def insert_dataset(apps, schema_editor):
        from signbank.dictionary.models import Language, SignLanguage

        Dataset = apps.get_model('dictionary', 'Dataset')
        Language = apps.get_model('dictionary', 'Language')
        SignLanguage = apps.get_model('dictionary', 'SignLanguage')

        l = Language.objects.get(pk=1)

        sl = SignLanguage(name="Default SL")
        sl.save()

        d = Dataset(name="Your dataset", description="Default dataset",
                    signlanguage=sl, acronym='YDS', default_language=l)
        d.save()

    operations = [
        migrations.RunPython(insert_dataset)
    ]
