# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-03-29 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0039_auto_20220127_1303'),
    ]

    def get_translation_fields(self):
        return [
            ('name_'+lang[0].replace('-', '_'), models.CharField(max_length=50, null=True))
            for lang in settings.LANGUAGES
        ]

    operations = [
        migrations.CreateModel(
            name='DerivationHistory',
            fields=[
                ('machine_value', models.IntegerField(primary_key=True, serialize=False, verbose_name='Machine value')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ] + get_translation_fields(None),
        ),
        migrations.CreateModel(
            name='DerivationHistoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('derivHist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.DerivationHistory')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Language')),
            ] + get_translation_fields(None),
        ),
        migrations.AddField(
            model_name='gloss',
            name='derivHistShadow',
            field=models.ManyToManyField(to='dictionary.DerivationHistory'),
        ),
        migrations.AlterUniqueTogether(
            name='derivationhistorytranslation',
            unique_together=set([('derivHist', 'language', 'name')]),
        ),
    ]
