# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-06-30 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0040_auto_20220329_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='count',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='definition',
            name='role',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=5, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='deletedglossormedia',
            name='annotation_idgloss',
            field=models.CharField(max_length=30, verbose_name='Annotation ID Gloss'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='absOriPalm',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('14', 'Backs towards each other'), ('4', 'Backwards'), ('8', 'Backwards > forwards'), ('2', 'Downwards'), ('11', 'Downwards, sidewards'), ('7', 'Forwards'), ('17', 'Forwards, downwards'), ('10', 'Forwards, sidewards'), ('6', 'Inwards'), ('15', 'Inwards > backwards'), ('9', 'Inwards, forwards'), ('13', 'Outwards'), ('16', 'Sidewards'), ('3', 'Towards each other'), ('5', 'Upwards'), ('12', 'Variable')], max_length=5, null=True, verbose_name='Absolute Orientation: Palm'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='contType',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('2', 'Brush'), ('6', 'Continuous'), ('15', 'Continuous > continuous'), ('8', 'Continuous > final'), ('13', 'Continuous > none'), ('12', 'Double'), ('4', 'Final'), ('14', 'Final > continuous'), ('16', 'Final > none'), ('5', 'Initial'), ('11', 'None > final'), ('9', 'None > initial')], max_length=5, null=True, verbose_name='Contact Type'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='domhndsh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('15', '1'), ('21', '1_curved'), ('37', '3'), ('191', '3 > O'), ('200', '3_curved'), ('35', '4'), ('201', '4 > 5'), ('192', '4 > O'), ('3', '5'), ('205', '5_claw'), ('203', '5_lax'), ('207', '5i'), ('30', '5m'), ('43', '5m_closed'), ('19', '5r'), ('49', '5r_closed'), ('48', '9'), ('24', 'A'), ('153', 'A > 5'), ('195', 'A > O'), ('2', 'A > T'), ('6', 'B'), ('173', 'B > A'), ('174', 'B > L'), ('175', 'B > S'), ('176', 'B > middlefinger'), ('138', 'B+1'), ('26', 'B_bent'), ('170', 'B_bent > B'), ('13', 'B_curved'), ('62', 'Baby_C'), ('206', 'Baby_C_extended'), ('38', 'Baby_O'), ('29', 'Baby_beak'), ('155', 'Baby_beak > A'), ('83', 'Baby_beak_open'), ('22', 'Beak'), ('17', 'Beak2'), ('85', 'Beak2_open'), ('152', 'Beak2_open_spread'), ('84', 'Beak_open'), ('87', 'Beak_open_spread'), ('86', 'Beak_spread'), ('27', 'C'), ('145', 'C > I'), ('136', 'C2_closed'), ('75', 'C2_spread'), ('12', 'C_spread'), ('34', 'D'), ('172', 'E'), ('39', 'F'), ('177', 'F > L'), ('197', 'Flower'), ('199', 'Flower > Beak_open_spread'), ('178', 'G'), ('59', 'Horns'), ('25', 'I'), ('181', 'I > L'), ('196', 'I > N'), ('182', 'I > W'), ('198', 'ILY'), ('179', 'K'), ('9', 'L'), ('193', 'L > O'), ('52', 'L2'), ('40', 'M'), ('183', 'M > V'), ('202', 'MRP'), ('80', 'Middle finger'), ('209', 'Middle finger > I'), ('4', 'Money'), ('14', 'N'), ('142', 'N > B'), ('184', 'N > E'), ('32', 'O'), ('139', 'O > 5m'), ('185', 'O > K'), ('135', 'Other'), ('180', 'P'), ('18', 'Q'), ('47', 'R'), ('8', 'S'), ('186', 'S > I'), ('204', 'S > L'), ('208', 'S > V'), ('28', 'T'), ('187', 'T > L'), ('188', 'T > V'), ('154', 'T_open'), ('5', 'V'), ('20', 'V_curved'), ('190', 'Variable'), ('16', 'W'), ('194', 'W > Beak2'), ('7', 'Y'), ('189', 'Y > R')], max_length=5, null=True, verbose_name='Strong Hand'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='domhndsh_letter',
            field=models.NullBooleanField(verbose_name='Strong hand letter'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='domhndsh_number',
            field=models.NullBooleanField(verbose_name='Strong hand number'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='final_domhndsh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('15', '1'), ('21', '1_curved'), ('37', '3'), ('191', '3 > O'), ('200', '3_curved'), ('35', '4'), ('201', '4 > 5'), ('192', '4 > O'), ('3', '5'), ('205', '5_claw'), ('203', '5_lax'), ('207', '5i'), ('30', '5m'), ('43', '5m_closed'), ('19', '5r'), ('49', '5r_closed'), ('48', '9'), ('24', 'A'), ('153', 'A > 5'), ('195', 'A > O'), ('2', 'A > T'), ('6', 'B'), ('173', 'B > A'), ('174', 'B > L'), ('175', 'B > S'), ('176', 'B > middlefinger'), ('138', 'B+1'), ('26', 'B_bent'), ('170', 'B_bent > B'), ('13', 'B_curved'), ('62', 'Baby_C'), ('206', 'Baby_C_extended'), ('38', 'Baby_O'), ('29', 'Baby_beak'), ('155', 'Baby_beak > A'), ('83', 'Baby_beak_open'), ('22', 'Beak'), ('17', 'Beak2'), ('85', 'Beak2_open'), ('152', 'Beak2_open_spread'), ('84', 'Beak_open'), ('87', 'Beak_open_spread'), ('86', 'Beak_spread'), ('27', 'C'), ('145', 'C > I'), ('136', 'C2_closed'), ('75', 'C2_spread'), ('12', 'C_spread'), ('34', 'D'), ('172', 'E'), ('39', 'F'), ('177', 'F > L'), ('197', 'Flower'), ('199', 'Flower > Beak_open_spread'), ('178', 'G'), ('59', 'Horns'), ('25', 'I'), ('181', 'I > L'), ('196', 'I > N'), ('182', 'I > W'), ('198', 'ILY'), ('179', 'K'), ('9', 'L'), ('193', 'L > O'), ('52', 'L2'), ('40', 'M'), ('183', 'M > V'), ('202', 'MRP'), ('80', 'Middle finger'), ('209', 'Middle finger > I'), ('4', 'Money'), ('14', 'N'), ('142', 'N > B'), ('184', 'N > E'), ('32', 'O'), ('139', 'O > 5m'), ('185', 'O > K'), ('135', 'Other'), ('180', 'P'), ('18', 'Q'), ('47', 'R'), ('8', 'S'), ('186', 'S > I'), ('204', 'S > L'), ('208', 'S > V'), ('28', 'T'), ('187', 'T > L'), ('188', 'T > V'), ('154', 'T_open'), ('5', 'V'), ('20', 'V_curved'), ('190', 'Variable'), ('16', 'W'), ('194', 'W > Beak2'), ('7', 'Y'), ('189', 'Y > R')], max_length=5, null=True, verbose_name='Final Dominant Handshape'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='final_loc',
            field=models.IntegerField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('21', 'Arm'), ('128', 'Armpit'), ('83', 'Back'), ('37', 'Back of head'), ('26', 'Belly'), ('14', 'Belly + forehead'), ('132', 'Belly > chest'), ('147', 'Between collarbones'), ('148', 'Between fingers'), ('143', 'Between legs'), ('149', 'Bottom/crotch'), ('135', 'Breasts'), ('136', 'Breasts_ipsi'), ('130', 'Bridge of the nose'), ('23', 'Cheek'), ('138', 'Cheek > cheek'), ('108', 'Cheek > chin'), ('72', 'Cheek contra'), ('16', 'Cheekbone'), ('8', 'Chest'), ('35', 'Chest > trunk'), ('74', 'Chest contra'), ('12', 'Chin'), ('70', 'Chin > chest'), ('28', 'Chin > neutral space'), ('102', 'Chin > weak hand: index finger'), ('33', 'Chin > weak hand: palm'), ('117', 'Chin > weak hand: thumb side'), ('133', 'Chin contra'), ('144', 'Crotch'), ('18', 'Ear'), ('84', 'Ear > cheek'), ('124', 'Ear > chest'), ('140', 'Earlobe'), ('142', 'East'), ('77', 'Elbow'), ('15', 'Eye'), ('120', 'Eye > neutral space'), ('129', 'Eyebrow'), ('17', 'Face'), ('110', 'Face > head'), ('93', 'Flank'), ('145', 'Flank/head'), ('7', 'Forehead'), ('34', 'Forehead > chest'), ('31', 'Forehead > chin'), ('106', 'Forehead > neutral space'), ('134', 'Forehead > shoulder'), ('104', 'Forehead > weak hand: palm'), ('64', 'Forehead contra'), ('10', 'Head'), ('119', 'Head + neutral space'), ('113', 'Head > chest'), ('127', 'Head > chest > shoulder'), ('69', 'Head > neutral space'), ('32', 'Head > shoulder'), ('107', 'Head > weak hand: palm'), ('150', 'Head contra'), ('30', 'Head ipsi'), ('94', 'Hip'), ('92', 'Horizontal plane'), ('85', 'Knee'), ('45', 'Leg'), ('151', 'Leg > waist'), ('95', 'Lower arm'), ('19', 'Mouth'), ('114', 'Mouth > cheek'), ('48', 'Mouth > chest'), ('13', 'Mouth > chin'), ('58', 'Mouth > weak hand'), ('112', 'Mouth > weak hand: palm'), ('152', 'Mouth contra'), ('137', 'Mouth ipsi'), ('9', 'Neck'), ('52', 'Neck > chest'), ('75', 'Neck contra'), ('3', 'Neutral space'), ('2', 'Neutral space > head'), ('121', 'Neutral space > nose'), ('29', 'Neutral space/weak hand: front'), ('22', 'Nose'), ('103', 'Nose > chin'), ('122', 'Nose > neutral space'), ('116', 'Parallel plane'), ('125', 'R-loc'), ('126', 'R-loc > R-loc'), ('4', 'Shoulder'), ('153', 'Shoulder > chest'), ('115', 'Shoulder > shoulder'), ('123', 'Shoulder > weak hand: palm'), ('55', 'Shoulder contra'), ('146', 'Teeth'), ('43', 'Temple'), ('78', 'Temple > chest'), ('79', 'Thumb'), ('27', 'Tongue'), ('97', 'Trunk'), ('54', 'Upper arm'), ('63', 'Upper lip'), ('118', 'Variable'), ('91', 'Virtual object'), ('5', 'Weak hand'), ('6', 'Weak hand > arm'), ('11', 'Weak hand: back'), ('109', 'Weak hand: base'), ('66', 'Weak hand: finger tips'), ('210', 'Weak hand: fingers'), ('90', 'Weak hand: front'), ('96', 'Weak hand: index finger'), ('211', 'Weak hand: knuckles'), ('98', 'Weak hand: middle finger'), ('36', 'Weak hand: palm'), ('88', 'Weak hand: pinkie'), ('101', 'Weak hand: pinkie side'), ('99', 'Weak hand: ring finger'), ('139', 'Weak hand: thenar'), ('59', 'Weak hand: thumb'), ('100', 'Weak hand: thumb side'), ('111', 'Weak hand: thumb side > arm'), ('89', 'Weak hand: web space'), ('141', 'West'), ('50', 'Wrist')], null=True, verbose_name='Final Primary Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='final_secondary_loc',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=20, null=True, verbose_name='Final Subordinate Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='final_subhndsh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('15', '1'), ('21', '1_curved'), ('37', '3'), ('191', '3 > O'), ('200', '3_curved'), ('35', '4'), ('201', '4 > 5'), ('192', '4 > O'), ('3', '5'), ('205', '5_claw'), ('203', '5_lax'), ('207', '5i'), ('30', '5m'), ('43', '5m_closed'), ('19', '5r'), ('49', '5r_closed'), ('48', '9'), ('24', 'A'), ('153', 'A > 5'), ('195', 'A > O'), ('2', 'A > T'), ('6', 'B'), ('173', 'B > A'), ('174', 'B > L'), ('175', 'B > S'), ('176', 'B > middlefinger'), ('138', 'B+1'), ('26', 'B_bent'), ('170', 'B_bent > B'), ('13', 'B_curved'), ('62', 'Baby_C'), ('206', 'Baby_C_extended'), ('38', 'Baby_O'), ('29', 'Baby_beak'), ('155', 'Baby_beak > A'), ('83', 'Baby_beak_open'), ('22', 'Beak'), ('17', 'Beak2'), ('85', 'Beak2_open'), ('152', 'Beak2_open_spread'), ('84', 'Beak_open'), ('87', 'Beak_open_spread'), ('86', 'Beak_spread'), ('27', 'C'), ('145', 'C > I'), ('136', 'C2_closed'), ('75', 'C2_spread'), ('12', 'C_spread'), ('34', 'D'), ('172', 'E'), ('39', 'F'), ('177', 'F > L'), ('197', 'Flower'), ('199', 'Flower > Beak_open_spread'), ('178', 'G'), ('59', 'Horns'), ('25', 'I'), ('181', 'I > L'), ('196', 'I > N'), ('182', 'I > W'), ('198', 'ILY'), ('179', 'K'), ('9', 'L'), ('193', 'L > O'), ('52', 'L2'), ('40', 'M'), ('183', 'M > V'), ('202', 'MRP'), ('80', 'Middle finger'), ('209', 'Middle finger > I'), ('4', 'Money'), ('14', 'N'), ('142', 'N > B'), ('184', 'N > E'), ('32', 'O'), ('139', 'O > 5m'), ('185', 'O > K'), ('135', 'Other'), ('180', 'P'), ('18', 'Q'), ('47', 'R'), ('8', 'S'), ('186', 'S > I'), ('204', 'S > L'), ('208', 'S > V'), ('28', 'T'), ('187', 'T > L'), ('188', 'T > V'), ('154', 'T_open'), ('5', 'V'), ('20', 'V_curved'), ('190', 'Variable'), ('16', 'W'), ('194', 'W > Beak2'), ('7', 'Y'), ('189', 'Y > R')], max_length=5, null=True, verbose_name='Final Subordinate Handshape'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='handCh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('7', 'Bending'), ('6', 'Closing'), ('48', 'Closing + rubbing'), ('44', 'Closing + wiggling'), ('32', 'Closing > opening'), ('51', 'Consecutive closing'), ('53', 'Consecutive opening'), ('8', 'Curving'), ('52', 'None > spreading'), ('5', 'Opening'), ('45', 'Opening + rubbing'), ('49', 'Opening + spreading'), ('47', 'Opening + wiggling'), ('38', 'Opening > closing'), ('39', 'Rubbing'), ('21', 'Spreading'), ('50', 'Unbending'), ('46', 'Uncurving'), ('10', 'Unspreading'), ('42', 'Wiggling')], max_length=5, null=True, verbose_name='Handshape Change'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='handedness',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('2', '1'), ('4', '2a'), ('7', '2n'), ('5', '2s'), ('6', 'X')], max_length=5, null=True, verbose_name='Handedness'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='initial_secondary_loc',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A')], max_length=20, null=True, verbose_name='Initial Subordinate Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='locPrimLH',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('21', 'Arm'), ('128', 'Armpit'), ('83', 'Back'), ('37', 'Back of head'), ('26', 'Belly'), ('14', 'Belly + forehead'), ('132', 'Belly > chest'), ('147', 'Between collarbones'), ('148', 'Between fingers'), ('143', 'Between legs'), ('149', 'Bottom/crotch'), ('135', 'Breasts'), ('136', 'Breasts_ipsi'), ('130', 'Bridge of the nose'), ('23', 'Cheek'), ('138', 'Cheek > cheek'), ('108', 'Cheek > chin'), ('72', 'Cheek contra'), ('16', 'Cheekbone'), ('8', 'Chest'), ('35', 'Chest > trunk'), ('74', 'Chest contra'), ('12', 'Chin'), ('70', 'Chin > chest'), ('28', 'Chin > neutral space'), ('102', 'Chin > weak hand: index finger'), ('33', 'Chin > weak hand: palm'), ('117', 'Chin > weak hand: thumb side'), ('133', 'Chin contra'), ('144', 'Crotch'), ('18', 'Ear'), ('84', 'Ear > cheek'), ('124', 'Ear > chest'), ('140', 'Earlobe'), ('142', 'East'), ('77', 'Elbow'), ('15', 'Eye'), ('120', 'Eye > neutral space'), ('129', 'Eyebrow'), ('17', 'Face'), ('110', 'Face > head'), ('93', 'Flank'), ('145', 'Flank/head'), ('7', 'Forehead'), ('34', 'Forehead > chest'), ('31', 'Forehead > chin'), ('106', 'Forehead > neutral space'), ('134', 'Forehead > shoulder'), ('104', 'Forehead > weak hand: palm'), ('64', 'Forehead contra'), ('10', 'Head'), ('119', 'Head + neutral space'), ('113', 'Head > chest'), ('127', 'Head > chest > shoulder'), ('69', 'Head > neutral space'), ('32', 'Head > shoulder'), ('107', 'Head > weak hand: palm'), ('150', 'Head contra'), ('30', 'Head ipsi'), ('94', 'Hip'), ('92', 'Horizontal plane'), ('85', 'Knee'), ('45', 'Leg'), ('151', 'Leg > waist'), ('95', 'Lower arm'), ('19', 'Mouth'), ('114', 'Mouth > cheek'), ('48', 'Mouth > chest'), ('13', 'Mouth > chin'), ('58', 'Mouth > weak hand'), ('112', 'Mouth > weak hand: palm'), ('152', 'Mouth contra'), ('137', 'Mouth ipsi'), ('9', 'Neck'), ('52', 'Neck > chest'), ('75', 'Neck contra'), ('3', 'Neutral space'), ('2', 'Neutral space > head'), ('121', 'Neutral space > nose'), ('29', 'Neutral space/weak hand: front'), ('22', 'Nose'), ('103', 'Nose > chin'), ('122', 'Nose > neutral space'), ('116', 'Parallel plane'), ('125', 'R-loc'), ('126', 'R-loc > R-loc'), ('4', 'Shoulder'), ('153', 'Shoulder > chest'), ('115', 'Shoulder > shoulder'), ('123', 'Shoulder > weak hand: palm'), ('55', 'Shoulder contra'), ('146', 'Teeth'), ('43', 'Temple'), ('78', 'Temple > chest'), ('79', 'Thumb'), ('27', 'Tongue'), ('97', 'Trunk'), ('54', 'Upper arm'), ('63', 'Upper lip'), ('118', 'Variable'), ('91', 'Virtual object'), ('5', 'Weak hand'), ('6', 'Weak hand > arm'), ('11', 'Weak hand: back'), ('109', 'Weak hand: base'), ('66', 'Weak hand: finger tips'), ('210', 'Weak hand: fingers'), ('90', 'Weak hand: front'), ('96', 'Weak hand: index finger'), ('211', 'Weak hand: knuckles'), ('98', 'Weak hand: middle finger'), ('36', 'Weak hand: palm'), ('88', 'Weak hand: pinkie'), ('101', 'Weak hand: pinkie side'), ('99', 'Weak hand: ring finger'), ('139', 'Weak hand: thenar'), ('59', 'Weak hand: thumb'), ('100', 'Weak hand: thumb side'), ('111', 'Weak hand: thumb side > arm'), ('89', 'Weak hand: web space'), ('141', 'West'), ('50', 'Wrist')], max_length=5, null=True, verbose_name='Placement Active Articulator LH'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='locprim',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('21', 'Arm'), ('128', 'Armpit'), ('83', 'Back'), ('37', 'Back of head'), ('26', 'Belly'), ('14', 'Belly + forehead'), ('132', 'Belly > chest'), ('147', 'Between collarbones'), ('148', 'Between fingers'), ('143', 'Between legs'), ('149', 'Bottom/crotch'), ('135', 'Breasts'), ('136', 'Breasts_ipsi'), ('130', 'Bridge of the nose'), ('23', 'Cheek'), ('138', 'Cheek > cheek'), ('108', 'Cheek > chin'), ('72', 'Cheek contra'), ('16', 'Cheekbone'), ('8', 'Chest'), ('35', 'Chest > trunk'), ('74', 'Chest contra'), ('12', 'Chin'), ('70', 'Chin > chest'), ('28', 'Chin > neutral space'), ('102', 'Chin > weak hand: index finger'), ('33', 'Chin > weak hand: palm'), ('117', 'Chin > weak hand: thumb side'), ('133', 'Chin contra'), ('144', 'Crotch'), ('18', 'Ear'), ('84', 'Ear > cheek'), ('124', 'Ear > chest'), ('140', 'Earlobe'), ('142', 'East'), ('77', 'Elbow'), ('15', 'Eye'), ('120', 'Eye > neutral space'), ('129', 'Eyebrow'), ('17', 'Face'), ('110', 'Face > head'), ('93', 'Flank'), ('145', 'Flank/head'), ('7', 'Forehead'), ('34', 'Forehead > chest'), ('31', 'Forehead > chin'), ('106', 'Forehead > neutral space'), ('134', 'Forehead > shoulder'), ('104', 'Forehead > weak hand: palm'), ('64', 'Forehead contra'), ('10', 'Head'), ('119', 'Head + neutral space'), ('113', 'Head > chest'), ('127', 'Head > chest > shoulder'), ('69', 'Head > neutral space'), ('32', 'Head > shoulder'), ('107', 'Head > weak hand: palm'), ('150', 'Head contra'), ('30', 'Head ipsi'), ('94', 'Hip'), ('92', 'Horizontal plane'), ('85', 'Knee'), ('45', 'Leg'), ('151', 'Leg > waist'), ('95', 'Lower arm'), ('19', 'Mouth'), ('114', 'Mouth > cheek'), ('48', 'Mouth > chest'), ('13', 'Mouth > chin'), ('58', 'Mouth > weak hand'), ('112', 'Mouth > weak hand: palm'), ('152', 'Mouth contra'), ('137', 'Mouth ipsi'), ('9', 'Neck'), ('52', 'Neck > chest'), ('75', 'Neck contra'), ('3', 'Neutral space'), ('2', 'Neutral space > head'), ('121', 'Neutral space > nose'), ('29', 'Neutral space/weak hand: front'), ('22', 'Nose'), ('103', 'Nose > chin'), ('122', 'Nose > neutral space'), ('116', 'Parallel plane'), ('125', 'R-loc'), ('126', 'R-loc > R-loc'), ('4', 'Shoulder'), ('153', 'Shoulder > chest'), ('115', 'Shoulder > shoulder'), ('123', 'Shoulder > weak hand: palm'), ('55', 'Shoulder contra'), ('146', 'Teeth'), ('43', 'Temple'), ('78', 'Temple > chest'), ('79', 'Thumb'), ('27', 'Tongue'), ('97', 'Trunk'), ('54', 'Upper arm'), ('63', 'Upper lip'), ('118', 'Variable'), ('91', 'Virtual object'), ('5', 'Weak hand'), ('6', 'Weak hand > arm'), ('11', 'Weak hand: back'), ('109', 'Weak hand: base'), ('66', 'Weak hand: finger tips'), ('210', 'Weak hand: fingers'), ('90', 'Weak hand: front'), ('96', 'Weak hand: index finger'), ('211', 'Weak hand: knuckles'), ('98', 'Weak hand: middle finger'), ('36', 'Weak hand: palm'), ('88', 'Weak hand: pinkie'), ('101', 'Weak hand: pinkie side'), ('99', 'Weak hand: ring finger'), ('139', 'Weak hand: thenar'), ('59', 'Weak hand: thumb'), ('100', 'Weak hand: thumb side'), ('111', 'Weak hand: thumb side > arm'), ('89', 'Weak hand: web space'), ('141', 'West'), ('50', 'Wrist')], max_length=20, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='locsecond',
            field=models.IntegerField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('21', 'Arm'), ('128', 'Armpit'), ('83', 'Back'), ('37', 'Back of head'), ('26', 'Belly'), ('14', 'Belly + forehead'), ('132', 'Belly > chest'), ('147', 'Between collarbones'), ('148', 'Between fingers'), ('143', 'Between legs'), ('149', 'Bottom/crotch'), ('135', 'Breasts'), ('136', 'Breasts_ipsi'), ('130', 'Bridge of the nose'), ('23', 'Cheek'), ('138', 'Cheek > cheek'), ('108', 'Cheek > chin'), ('72', 'Cheek contra'), ('16', 'Cheekbone'), ('8', 'Chest'), ('35', 'Chest > trunk'), ('74', 'Chest contra'), ('12', 'Chin'), ('70', 'Chin > chest'), ('28', 'Chin > neutral space'), ('102', 'Chin > weak hand: index finger'), ('33', 'Chin > weak hand: palm'), ('117', 'Chin > weak hand: thumb side'), ('133', 'Chin contra'), ('144', 'Crotch'), ('18', 'Ear'), ('84', 'Ear > cheek'), ('124', 'Ear > chest'), ('140', 'Earlobe'), ('142', 'East'), ('77', 'Elbow'), ('15', 'Eye'), ('120', 'Eye > neutral space'), ('129', 'Eyebrow'), ('17', 'Face'), ('110', 'Face > head'), ('93', 'Flank'), ('145', 'Flank/head'), ('7', 'Forehead'), ('34', 'Forehead > chest'), ('31', 'Forehead > chin'), ('106', 'Forehead > neutral space'), ('134', 'Forehead > shoulder'), ('104', 'Forehead > weak hand: palm'), ('64', 'Forehead contra'), ('10', 'Head'), ('119', 'Head + neutral space'), ('113', 'Head > chest'), ('127', 'Head > chest > shoulder'), ('69', 'Head > neutral space'), ('32', 'Head > shoulder'), ('107', 'Head > weak hand: palm'), ('150', 'Head contra'), ('30', 'Head ipsi'), ('94', 'Hip'), ('92', 'Horizontal plane'), ('85', 'Knee'), ('45', 'Leg'), ('151', 'Leg > waist'), ('95', 'Lower arm'), ('19', 'Mouth'), ('114', 'Mouth > cheek'), ('48', 'Mouth > chest'), ('13', 'Mouth > chin'), ('58', 'Mouth > weak hand'), ('112', 'Mouth > weak hand: palm'), ('152', 'Mouth contra'), ('137', 'Mouth ipsi'), ('9', 'Neck'), ('52', 'Neck > chest'), ('75', 'Neck contra'), ('3', 'Neutral space'), ('2', 'Neutral space > head'), ('121', 'Neutral space > nose'), ('29', 'Neutral space/weak hand: front'), ('22', 'Nose'), ('103', 'Nose > chin'), ('122', 'Nose > neutral space'), ('116', 'Parallel plane'), ('125', 'R-loc'), ('126', 'R-loc > R-loc'), ('4', 'Shoulder'), ('153', 'Shoulder > chest'), ('115', 'Shoulder > shoulder'), ('123', 'Shoulder > weak hand: palm'), ('55', 'Shoulder contra'), ('146', 'Teeth'), ('43', 'Temple'), ('78', 'Temple > chest'), ('79', 'Thumb'), ('27', 'Tongue'), ('97', 'Trunk'), ('54', 'Upper arm'), ('63', 'Upper lip'), ('118', 'Variable'), ('91', 'Virtual object'), ('5', 'Weak hand'), ('6', 'Weak hand > arm'), ('11', 'Weak hand: back'), ('109', 'Weak hand: base'), ('66', 'Weak hand: finger tips'), ('210', 'Weak hand: fingers'), ('90', 'Weak hand: front'), ('96', 'Weak hand: index finger'), ('211', 'Weak hand: knuckles'), ('98', 'Weak hand: middle finger'), ('36', 'Weak hand: palm'), ('88', 'Weak hand: pinkie'), ('101', 'Weak hand: pinkie side'), ('99', 'Weak hand: ring finger'), ('139', 'Weak hand: thenar'), ('59', 'Weak hand: thumb'), ('100', 'Weak hand: thumb side'), ('111', 'Weak hand: thumb side > arm'), ('89', 'Weak hand: web space'), ('141', 'West'), ('50', 'Wrist')], null=True, verbose_name='Secondary Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='movDir',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('5', 'Backwards'), ('103', 'Backwards + contralateral'), ('87', 'Backwards + downwards'), ('93', 'Backwards + ipsilateral'), ('72', 'Backwards + upwards'), ('6', 'Backwards > downwards'), ('2', 'Backwards > forwards'), ('15', 'Backwards/forwards'), ('50', 'Contralateral'), ('53', 'Contralateral + downwards'), ('54', 'Contralateral + forwards'), ('52', 'Contralateral + upwards'), ('3', 'Contralateral > forwards'), ('102', 'Contralateral > ipsilateral'), ('98', 'Distal'), ('8', 'Downwards'), ('105', 'Downwards + contralateral/ipsilateral'), ('56', 'Downwards + forwards'), ('57', 'Downwards + ipsilateral'), ('58', 'Downwards + ipsilateral > downwards'), ('94', 'Downwards + towards'), ('59', 'Downwards > contralateral'), ('4', 'Downwards > forwards'), ('55', 'Downwards > ipsilateral'), ('104', 'Downwards > upwards'), ('69', 'Downwards/upwards'), ('90', 'Downwards/upwards + ipsilateral'), ('16', 'Forwards'), ('60', 'Forwards + ipsilateral'), ('61', 'Forwards + upwards'), ('107', 'Forwards > backwards'), ('63', 'Forwards > contralateral'), ('17', 'Forwards > downwards'), ('62', 'Forwards > ipsilateral'), ('64', 'Forwards > ipsilateral > forwards'), ('92', 'Forwards > upwards'), ('100', 'From location'), ('51', 'Ipsilateral'), ('91', 'Ipsilateral + up and down'), ('65', 'Ipsilateral + upwards'), ('71', 'Ipsilateral > contralateral'), ('68', 'Ipsilateral > downwards'), ('66', 'Ipsilateral > downwards > contralateral'), ('67', 'Ipsilateral > upwards'), ('89', 'Ipsilateral and contralateral'), ('88', 'Ipsilateral/contralateral'), ('99', 'Lateral'), ('95', 'Proximal'), ('46', 'To and fro'), ('96', 'Towards location'), ('70', 'Up and down'), ('32', 'Upwards'), ('33', 'Upwards > downwards'), ('73', 'Upwards > forwards > downwards'), ('106', 'Upwards > ipsilateral'), ('49', 'Variable')], max_length=5, null=True, verbose_name='Movement Direction'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='movSh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('4', 'Arc'), ('37', 'Circle'), ('46', 'Cross'), ('44', 'Motivated shape'), ('45', 'Spiral'), ('6', 'Straight'), ('12', 'Zigzag')], max_length=5, null=True, verbose_name='Movement Shape'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='namEnt',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('6', 'Brand'), ('17', 'Company'), ('15', 'Continent'), ('7', 'Country'), ('8', 'Device'), ('19', 'Drink'), ('12', 'Event'), ('21', 'Food'), ('22', 'Language'), ('20', 'Magazine'), ('13', 'Newspaper'), ('16', 'Organisation'), ('2', 'Person'), ('4', 'Place'), ('11', 'Place nickname'), ('9', 'Product'), ('10', 'Project'), ('3', 'Public figure'), ('5', 'Region'), ('14', 'Story character'), ('18', 'Team')], max_length=5, null=True, verbose_name='Named Entity'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='oriCh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('3', 'Extension'), ('17', 'Extension + pronation'), ('13', 'Extension > flexion'), ('14', 'Extension/flexion'), ('4', 'Flexion'), ('15', 'Flexion > extension'), ('8', 'Pronation'), ('9', 'Pronation/supination'), ('12', 'Radial and ulnar flexion'), ('5', 'Radial flexion'), ('2', 'Rotation'), ('7', 'Supination'), ('16', 'Supination > pronation'), ('6', 'Ulnar flexion')], max_length=5, null=True, verbose_name='Orientation Change'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='relOriLoc',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('37', 'AO: fingers-contra'), ('36', 'AO: fingers-down'), ('35', 'AO: fingers-up'), ('41', 'AO: palm-backwards'), ('31', 'AO: palm-down'), ('42', 'AO: palm-down > palm-up'), ('40', 'AO: palm-forwards'), ('32', 'AO: palm-inwards'), ('33', 'AO: palm-outwards'), ('30', 'AO: palm-up'), ('34', 'AO: palm-up/down'), ('8', 'Back'), ('38', 'Back > palm'), ('58', 'Back > ulnar'), ('27', 'Back/palm'), ('28', 'Back/palm > palm'), ('3', 'Base'), ('29', 'Counting'), ('4', 'Finger tips'), ('24', 'Finger tips/base'), ('26', 'Fingerspelling'), ('25', 'Front'), ('7', 'Palm'), ('39', 'Palm > ulnar'), ('5', 'Radial'), ('2', 'Radial/ulnar'), ('6', 'Ulnar')], max_length=5, null=True, verbose_name='Relative Orientation: Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='relOriMov',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('7', 'Back'), ('25', 'Back + base'), ('55', 'Back + radial'), ('31', 'Back + ulnar'), ('46', 'Back > finger tips'), ('45', 'Back > front'), ('15', 'Back > palm'), ('56', 'Back > radial'), ('38', 'Back/base'), ('48', 'Back/finger tips'), ('23', 'Back/palm'), ('22', 'Base'), ('24', 'Base + front'), ('26', 'Base + palm'), ('27', 'Base + ulnar'), ('50', 'Base > back'), ('28', 'Base > base'), ('39', 'Base > front'), ('37', 'Base > palm'), ('29', 'Base > ulnar'), ('36', 'Base/front'), ('4', 'Finger tips'), ('58', 'Finger tips > back'), ('44', 'Finger tips > base'), ('43', 'Finger tips > palm'), ('35', 'Finger tips/base'), ('53', 'Finger tips/ulnar'), ('6', 'Front'), ('10', 'Front + ulnar'), ('54', 'Front > back'), ('57', 'Front/palm'), ('3', 'Palm'), ('49', 'Palm + radial'), ('52', 'Palm + radial/ulnar'), ('40', 'Palm + ulnar'), ('33', 'Palm > back'), ('30', 'Palm > base'), ('5', 'Radial'), ('34', 'Radial > ulnar'), ('32', 'Radial/ulnar'), ('2', 'Ulnar'), ('47', 'Ulnar > base'), ('41', 'Ulnar > base > radial'), ('42', 'Ulnar > front'), ('17', 'Ulnar > palm'), ('19', 'Ulnar > palm > radial'), ('51', 'Ulnar > radial'), ('9', 'Variable')], max_length=5, null=True, verbose_name='Relative Orientation: Movement'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='relatArtic',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('45', 'Above'), ('47', 'Above/below'), ('50', 'Around'), ('43', 'Back'), ('46', 'Below'), ('41', 'Cross'), ('42', 'Front'), ('44', 'Front/back'), ('48', 'Inside'), ('27', 'Interlocked'), ('40', 'Interwoven'), ('49', 'Next-to')], max_length=5, null=True, verbose_name='Relation between Articulators'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='semField',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('4', 'Animal'), ('5', 'Arithmetic'), ('6', 'Arts'), ('7', 'Body part'), ('8', 'Car'), ('10', 'City'), ('11', 'Clothing'), ('12', 'Colour'), ('9', 'Cooking'), ('2', 'Day'), ('3', 'Deaf'), ('13', 'Drink'), ('14', 'Education'), ('52', 'Emotion'), ('15', 'Family'), ('54', 'Fruit'), ('18', 'Furniture'), ('51', 'Geography'), ('56', 'Gorilla'), ('19', 'Government'), ('21', 'Health'), ('23', 'Language act'), ('24', 'Law'), ('50', 'Linguistics'), ('25', 'Material'), ('26', 'Metalinguistic'), ('27', 'Mind'), ('28', 'Money'), ('53', 'Month'), ('29', 'Nature'), ('30', 'Number'), ('31', 'People'), ('32', 'Physical act'), ('33', 'Quality'), ('34', 'Quantity'), ('35', 'Question'), ('36', 'Recreation'), ('55', 'Religion'), ('37', 'Salutation'), ('38', 'Sensation'), ('39', 'Sexuality'), ('40', 'Shape'), ('41', 'Shopping'), ('49', 'Space'), ('42', 'Sport'), ('43', 'Technology'), ('44', 'Time'), ('45', 'Travel'), ('46', 'Utensil'), ('47', 'Weather'), ('48', 'Work')], max_length=5, null=True, verbose_name='Semantic Field'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='subhndsh',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('15', '1'), ('21', '1_curved'), ('37', '3'), ('191', '3 > O'), ('200', '3_curved'), ('35', '4'), ('201', '4 > 5'), ('192', '4 > O'), ('3', '5'), ('205', '5_claw'), ('203', '5_lax'), ('207', '5i'), ('30', '5m'), ('43', '5m_closed'), ('19', '5r'), ('49', '5r_closed'), ('48', '9'), ('24', 'A'), ('153', 'A > 5'), ('195', 'A > O'), ('2', 'A > T'), ('6', 'B'), ('173', 'B > A'), ('174', 'B > L'), ('175', 'B > S'), ('176', 'B > middlefinger'), ('138', 'B+1'), ('26', 'B_bent'), ('170', 'B_bent > B'), ('13', 'B_curved'), ('62', 'Baby_C'), ('206', 'Baby_C_extended'), ('38', 'Baby_O'), ('29', 'Baby_beak'), ('155', 'Baby_beak > A'), ('83', 'Baby_beak_open'), ('22', 'Beak'), ('17', 'Beak2'), ('85', 'Beak2_open'), ('152', 'Beak2_open_spread'), ('84', 'Beak_open'), ('87', 'Beak_open_spread'), ('86', 'Beak_spread'), ('27', 'C'), ('145', 'C > I'), ('136', 'C2_closed'), ('75', 'C2_spread'), ('12', 'C_spread'), ('34', 'D'), ('172', 'E'), ('39', 'F'), ('177', 'F > L'), ('197', 'Flower'), ('199', 'Flower > Beak_open_spread'), ('178', 'G'), ('59', 'Horns'), ('25', 'I'), ('181', 'I > L'), ('196', 'I > N'), ('182', 'I > W'), ('198', 'ILY'), ('179', 'K'), ('9', 'L'), ('193', 'L > O'), ('52', 'L2'), ('40', 'M'), ('183', 'M > V'), ('202', 'MRP'), ('80', 'Middle finger'), ('209', 'Middle finger > I'), ('4', 'Money'), ('14', 'N'), ('142', 'N > B'), ('184', 'N > E'), ('32', 'O'), ('139', 'O > 5m'), ('185', 'O > K'), ('135', 'Other'), ('180', 'P'), ('18', 'Q'), ('47', 'R'), ('8', 'S'), ('186', 'S > I'), ('204', 'S > L'), ('208', 'S > V'), ('28', 'T'), ('187', 'T > L'), ('188', 'T > V'), ('154', 'T_open'), ('5', 'V'), ('20', 'V_curved'), ('190', 'Variable'), ('16', 'W'), ('194', 'W > Beak2'), ('7', 'Y'), ('189', 'Y > R')], max_length=5, null=True, verbose_name='Weak Hand'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='subhndsh_letter',
            field=models.NullBooleanField(verbose_name='Weak hand letter'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='subhndsh_number',
            field=models.NullBooleanField(verbose_name='Weak hand number'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='weakdrop',
            field=models.NullBooleanField(verbose_name='Weak Drop'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='weakprop',
            field=models.NullBooleanField(verbose_name='Weak Prop'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='wordClass',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('5', 'Adjective'), ('8', 'Adverb'), ('7', 'Interjection'), ('2', 'Noun'), ('6', 'Noun or verb'), ('4', 'Particle'), ('3', 'Verb')], max_length=5, null=True, verbose_name='Word class'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='wordClass2',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('5', 'Adjective'), ('8', 'Adverb'), ('7', 'Interjection'), ('2', 'Noun'), ('6', 'Noun or verb'), ('4', 'Particle'), ('3', 'Verb')], max_length=5, null=True, verbose_name='Word class 2'),
        ),
        migrations.AlterField(
            model_name='handshape',
            name='hsAperture',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('4', 'Closed'), ('3', 'Open')], max_length=5, null=True, verbose_name='Aperture'),
        ),
        migrations.AlterField(
            model_name='handshape',
            name='hsFingConf',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('8', 'bent'), ('12', 'closed'), ('13', 'crossed'), ('5', 'curved'), ('3', 'extended'), ('9', 'flat'), ('11', 'flat-closed'), ('10', 'flat-open'), ('14', 'lax'), ('4', 'open')], max_length=5, null=True, verbose_name='Finger configuration'),
        ),
        migrations.AlterField(
            model_name='handshape',
            name='hsFingConf2',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('8', 'bent'), ('12', 'closed'), ('13', 'crossed'), ('5', 'curved'), ('3', 'extended'), ('9', 'flat'), ('11', 'flat-closed'), ('10', 'flat-open'), ('14', 'lax'), ('4', 'open')], max_length=5, null=True, verbose_name='Finger configuration 2'),
        ),
        migrations.AlterField(
            model_name='handshape',
            name='hsFingSel',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('34', ''), ('26', 'I'), ('24', 'IM'), ('21', 'IMP'), ('20', 'IMR'), ('19', 'IMRP'), ('25', 'IP'), ('23', 'IR'), ('22', 'IRP'), ('30', 'M'), ('29', 'MP'), ('28', 'MR'), ('27', 'MRP'), ('33', 'P'), ('32', 'R'), ('31', 'RP'), ('18', 'T'), ('14', 'TI'), ('8', 'TIM'), ('5', 'TIMP'), ('4', 'TIMR'), ('3', 'TIMRP'), ('10', 'TIP'), ('9', 'TIR'), ('6', 'TIRP'), ('15', 'TM'), ('12', 'TMP'), ('11', 'TMR'), ('7', 'TMRP'), ('17', 'TP'), ('16', 'TR'), ('13', 'TRP')], max_length=5, null=True, verbose_name='Finger selection'),
        ),
        migrations.AlterField(
            model_name='handshape',
            name='hsFingSel2',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('34', ''), ('26', 'I'), ('24', 'IM'), ('21', 'IMP'), ('20', 'IMR'), ('19', 'IMRP'), ('25', 'IP'), ('23', 'IR'), ('22', 'IRP'), ('30', 'M'), ('29', 'MP'), ('28', 'MR'), ('27', 'MRP'), ('33', 'P'), ('32', 'R'), ('31', 'RP'), ('18', 'T'), ('14', 'TI'), ('8', 'TIM'), ('5', 'TIMP'), ('4', 'TIMR'), ('3', 'TIMRP'), ('10', 'TIP'), ('9', 'TIR'), ('6', 'TIRP'), ('15', 'TM'), ('12', 'TMP'), ('11', 'TMR'), ('7', 'TMRP'), ('17', 'TP'), ('16', 'TR'), ('13', 'TRP')], max_length=5, null=True, verbose_name='Finger selection 2'),
        ),
        migrations.AlterField(
            model_name='handshape',
            name='hsFingUnsel',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('34', ''), ('26', 'I'), ('24', 'IM'), ('21', 'IMP'), ('20', 'IMR'), ('19', 'IMRP'), ('25', 'IP'), ('23', 'IR'), ('22', 'IRP'), ('30', 'M'), ('29', 'MP'), ('28', 'MR'), ('27', 'MRP'), ('33', 'P'), ('32', 'R'), ('31', 'RP'), ('18', 'T'), ('14', 'TI'), ('8', 'TIM'), ('5', 'TIMP'), ('4', 'TIMR'), ('3', 'TIMRP'), ('10', 'TIP'), ('9', 'TIR'), ('6', 'TIRP'), ('15', 'TM'), ('12', 'TMP'), ('11', 'TMR'), ('7', 'TMRP'), ('17', 'TP'), ('16', 'TR'), ('13', 'TRP')], max_length=5, null=True, verbose_name='Unselected fingers'),
        ),
        migrations.AlterField(
            model_name='handshape',
            name='hsNumSel',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('7', 'all'), ('6', 'four'), ('3', 'one'), ('5', 'three'), ('4', 'two')], max_length=5, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='handshape',
            name='hsSpread',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('6', 'Crossed'), ('4', 'Spread'), ('5', 'Stacked'), ('3', 'Unspread')], max_length=5, null=True, verbose_name='Spreading'),
        ),
        migrations.AlterField(
            model_name='handshape',
            name='hsThumb',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('3', 'Extended'), ('4', 'Opposed')], max_length=5, null=True, verbose_name='Thumb'),
        ),
        migrations.AlterField(
            model_name='morpheme',
            name='mrpType',
            field=models.CharField(blank=True, choices=[('0', '-'), ('1', 'N/A'), ('13', 'Articulator: Aperture'), ('14', 'Articulator: Finger shape'), ('12', 'Articulator: NSF'), ('2', 'Articulator: SF'), ('36', 'Articulator: Self-referential'), ('15', 'Articulator: Spreading'), ('33', 'FMU Cluster'), ('11', 'Hands: Arrangement'), ('10', 'Hands: Handedness'), ('35', 'Hands: Symmetry'), ('27', 'Location: Contact type'), ('25', 'Location: Location'), ('37', 'Movement: Hand-internal'), ('28', 'Movement: Local'), ('31', 'Movement: Manner'), ('32', 'Movement: Path direction'), ('29', 'Movement: Path shape'), ('30', 'Movement: Repetition'), ('34', 'Movement: Syllabicity'), ('23', 'Orientation (absolute)'), ('5', 'Orientation (relative)')], max_length=5, null=True, verbose_name='Has morpheme type'),
        ),
        migrations.AlterField(
            model_name='othermedia',
            name='type',
            field=models.CharField(choices=[('0', '-'), ('1', 'N/A'), ('2', 'Alternative citation form'), ('3', 'Citation form with mouthing'), ('12', 'Definition'), ('11', 'Elicitation image'), ('10', 'Handy signs: experiments (mouthing, long)'), ('5', 'Handy signs: experiments (mouthing, short)'), ('8', 'Handy signs: experiments (no mouthing, long)'), ('9', 'Handy signs: experiments (no mouthing, short)'), ('4', 'Sign in sentence context'), ('6', 'SignPhon: citation form'), ('7', 'SignPhon: sentence')], max_length=5),
        ),
        migrations.AlterField(
            model_name='relation',
            name='role',
            field=models.CharField(choices=[('homonym', 'Homonym'), ('synonym', 'Synonym'), ('variant', 'Variant'), ('antonym', 'Antonym'), ('hyponym', 'Hyponym'), ('hypernym', 'Hypernym'), ('seealso', 'See Also'), ('paradigm', 'Handshape Paradigm')], max_length=20),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'm'), ('Female', 'f'), ('Other', 'o')], max_length=1),
        ),
    ]
