# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-23 10:45
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0041_auto_20200623_1231'),
    ]

    def get_migration_addfields(self, model_name, name_base, field):
        addfields = []
        for lang in settings.LANGUAGES:
            addfields.append(
                migrations.AddField(model_name=model_name, name=name_base+'_'+lang[0].replace('-', '_'), field=field)
            )
        return addfields

    operations = get_migration_addfields(None, 'fieldchoice', 'name', models.CharField(max_length=50, null=True))\
                 + get_migration_addfields(None, 'handshape', 'name', models.CharField(max_length=50, null=True))
