# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-23 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0041_auto_20200623_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldchoice',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fieldchoice',
            name='name_nl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fieldchoice',
            name='name_zh_hans',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='handshape',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='English name'),
        ),
        migrations.AddField(
            model_name='handshape',
            name='name_nl',
            field=models.CharField(max_length=50, null=True, verbose_name='English name'),
        ),
        migrations.AddField(
            model_name='handshape',
            name='name_zh_hans',
            field=models.CharField(max_length=50, null=True, verbose_name='English name'),
        ),
    ]
