# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-06 12:50
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion

from signbank.dictionary.models import MorphologyDefinition, FieldChoiceForeignKey

import importlib
migration_0039 = importlib.import_module('signbank.dictionary.migrations.0039_auto_20200910_1020')

def move_fieldchoice_choice(apps, schema_editor):
    migration_0039.move_fieldchoice_choice_for_class(apps, schema_editor, MorphologyDefinition)

class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0044_auto_20201125_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='morphologydefinition',
            name='role_fk',
            field=FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                        related_name='definition', to='dictionary.FieldChoice',),
        ),
        migrations.RunPython(move_fieldchoice_choice),
    ]
