# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-23 10:31
# Revised Dependency 2022-07-01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0044_auto_20200623_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handshape',
            old_name='english_name',
            new_name='name',
        ),
    ]
