# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-06 12:50
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion

from signbank.dictionary.models import MorphologyDefinition, FieldChoiceForeignKey

import importlib
migration_0039 = importlib.import_module('signbank.dictionary.migrations.0039_auto_20200910_1020')

def move_fieldchoice_choice(apps, schema_editor):
    migration_0039.move_fieldchoice_choice_for_class(apps, schema_editor, MorphologyDefinition)

class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0045_auto_20210106_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morphologydefinition',
            name='role',
        ),
        migrations.RenameField(
            model_name='morphologydefinition',
            old_name='role_fk',
            new_name='role',
        ),
    ]
