# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-02 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import signbank.dictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0045_auto_20210106_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='gloss',
            name='domhndsh_handshapefk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strong_hand_handshapefk', to='dictionary.Handshape', verbose_name='Strong Hand'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='final_domhndsh_handshapefk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_dominant_handshape_handshapefk', to='dictionary.Handshape', verbose_name='Final Dominant Handshape'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='final_subhndsh_handshapefk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_subordinate_handshape_handshapefk', to='dictionary.Handshape', verbose_name='Final Subordinate Handshape'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='subhndsh_handshapefk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weak_hand_handshapefk', to='dictionary.Handshape', verbose_name='Weak Hand'),
        ),
    ]
