# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-02 08:16
from __future__ import unicode_literals

from django.db import migrations


def add_default_handshapes(apps, schema_editor):
    """
    Add 0 and 1 choices to every Handshape category
    :param apps:
    :param schema_editor:
    :return:
    """
    Handshape = apps.get_model('dictionary', 'Handshape')

    new_handshape_0, created = Handshape.objects.get_or_create(name='-', machine_value=0)
    if created:
        new_handshape_0.name_en = '-'
        new_handshape_0.name_nl = '-'
        new_handshape_0.name_zh_hans = '-'
        new_handshape_0.save()

    new_handshape_1, created = Handshape.objects.get_or_create(name='N/A', machine_value=1)
    new_handshape_1.name_en = 'N/A'
    new_handshape_1.name_nl = 'N/A'
    new_handshape_1.name_zh_hans = 'N/A'
    new_handshape_1.save()


def copy_handshape_values(apps, schema_editor):
    Gloss = apps.get_model('dictionary', 'Gloss')
    Handshape = apps.get_model('dictionary', 'Handshape')

    # Put all handshapes in a dict for convenient lookup
    handshapes = dict([(handshape.machine_value, handshape) for handshape in Handshape.objects.all()])

    # Copy values for each Gloss
    for gloss in Gloss.objects.all():
        if gloss.domhndsh_fk:
            gloss.domhndsh_handshapefk = handshapes[gloss.domhndsh_fk.machine_value]
        if gloss.subhndsh_fk:
            gloss.subhndsh_handshapefk = handshapes[gloss.subhndsh_fk.machine_value]
        if gloss.final_domhndsh_fk:
            gloss.final_domhndsh_handshapefk = handshapes[gloss.final_domhndsh_fk.machine_value]
        if gloss.final_subhndsh_fk:
            gloss.final_subhndsh_handshapefk = handshapes[gloss.final_subhndsh_fk.machine_value]
        gloss.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0047_auto_20210602_1006'),
    ]

    operations = [
        migrations.RunPython(add_default_handshapes),
        migrations.RunPython(copy_handshape_values),
    ]
