# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-02 08:16
from __future__ import unicode_literals

from django.db import migrations



def copy_handshape_values(apps, schema_editor):
    Gloss = apps.get_model('dictionary', 'Gloss')
    Handshape = apps.get_model('dictionary', 'Handshape')

    # Put all handshapes in a dict for convenient lookup
    handshapes = dict([(handshape.machine_value, handshape) for handshape in Handshape.objects.all()])

    # Copy values for each Gloss
    for gloss in Gloss.objects.all():
        if gloss.domhndsh:
            gloss.domhndsh_handshapefk = handshapes[gloss.domhndsh.machine_value]
        if gloss.subhndsh:
            gloss.subhndsh_handshapefk = handshapes[gloss.subhndsh.machine_value]
        if gloss.final_domhndsh:
            gloss.final_domhndsh_handshapefk = handshapes[gloss.final_domhndsh.machine_value]
        if gloss.final_subhndsh:
            gloss.final_subhndsh_handshapefk = handshapes[gloss.final_subhndsh.machine_value]
        gloss.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0047_auto_20210602_1006'),
    ]

    operations = [
        migrations.RunPython(copy_handshape_values),
    ]
