# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-10-20 13:59
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import signbank.dictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0048_auto_20210602_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='handshape',
            name='field_color',
            field=colorfield.fields.ColorField(default='ffffff', max_length=18),
        ),
    ]
