# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-02 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import signbank.dictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0049_auto_20210602_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloss',
            name='domhndsh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strong_hand', to='dictionary.Handshape', verbose_name='Strong Hand'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='final_domhndsh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_dominant_handshape', to='dictionary.Handshape', verbose_name='Final Dominant Handshape'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='final_subhndsh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_subordinate_handshape', to='dictionary.Handshape', verbose_name='Final Subordinate Handshape'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='subhndsh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weak_hand', to='dictionary.Handshape', verbose_name='Weak Hand'),
        ),
    ]
