# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-10-21 11:10
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import signbank.dictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0049_auto_20221020_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivationhistory',
            name='field_color',
            field=colorfield.fields.ColorField(default='ffffff', max_length=18),
        ),
        migrations.AddField(
            model_name='derivationhistory',
            name='name_en',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='derivationhistory',
            name='name_nl',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='derivationhistory',
            name='name_zh_hans',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='semanticfield',
            name='field_color',
            field=colorfield.fields.ColorField(default='ffffff', max_length=18),
        ),
        migrations.AddField(
            model_name='semanticfield',
            name='name_en',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='semanticfield',
            name='name_nl',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='semanticfield',
            name='name_zh_hans',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
