# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-22 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import signbank.dictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0052_auto_20221122_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldchoice',
            name='field',
            field=models.CharField(choices=[('AbsOriFing', 'AbsOriFing'), ('AbsOriPalm', 'AbsOriPalm'), ('Aperture', 'Aperture'), ('ContactType', 'ContactType'), ('DominantHandFlexion', 'DominantHandFlexion'), ('DominantHandSelectedFingers', 'DominantHandSelectedFingers'), ('FingerSelection', 'FingerSelection'), ('Handedness', 'Handedness'), ('iconicity', 'iconicity'), ('HandshapeChange', 'HandshapeChange'), ('JointConfiguration', 'JointConfiguration'), ('Location', 'Location'), ('MinorLocation', 'MinorLocation'), ('MorphemeType', 'MorphemeType'), ('MorphologyType', 'MorphologyType'), ('MovementDir', 'MovementDir'), ('MovementMan', 'MovementMan'), ('MovementShape', 'MovementShape'), ('NamedEntity', 'NamedEntity'), ('NoteType', 'NoteType'), ('OriChange', 'OriChange'), ('OtherMediaType', 'OtherMediaType'), ('PathOnPath', 'PathOnPath'), ('Quantity', 'Quantity'), ('RelOriLoc', 'RelOriLoc'), ('RelOriMov', 'RelOriMov'), ('RelatArtic', 'RelatArtic'), ('Spreading', 'Spreading'), ('Thumb', 'Thumb'), ('Valence', 'Valence'), ('WordClass', 'WordClass')], max_length=50),
        ),
    ]
