# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-23 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import signbank.dictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0053_auto_20221122_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldchoice',
            name='chinese_name',
        ),
        migrations.RemoveField(
            model_name='fieldchoice',
            name='dutch_name',
        ),
        migrations.RemoveField(
            model_name='handshape',
            name='chinese_name',
        ),
        migrations.RemoveField(
            model_name='handshape',
            name='dutch_name',
        ),
    ]
