# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-23 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import signbank.dictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0054_auto_20221123_1416'),
    ]

    operations = [
    ]
