# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-23 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import signbank.dictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0054_auto_20221123_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivationhistory',
            name='name_ar',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='derivationhistory',
            name='name_he',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fieldchoice',
            name='name_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fieldchoice',
            name='name_he',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='handshape',
            name='name_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='handshape',
            name='name_he',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='name_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='name_he',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='semanticfield',
            name='name_ar',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='semanticfield',
            name='name_he',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
