# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-02-03 13:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import signbank.dictionary.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0055_auto_20221123_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiselect', models.BooleanField(default=True, help_text='Is this a multiselect parameter?', verbose_name='Multiple Select')),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queryDate', models.DateTimeField(auto_now=True, verbose_name='Query Date')),
                ('queryName', models.CharField(blank=True, help_text='Abbreviation for the query', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QueryParameterDerivationHistory',
            fields=[
                ('queryparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dictionary.QueryParameter')),
                ('fieldName', models.CharField(choices=[('derivHist', 'derivHist')], max_length=20, verbose_name='Derivation History')),
                ('fieldValue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.DerivationHistory')),
            ],
            bases=('dictionary.queryparameter',),
        ),
        migrations.CreateModel(
            name='QueryParameterFieldChoice',
            fields=[
                ('queryparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dictionary.QueryParameter')),
                ('fieldName', models.CharField(choices=[('wordClass', 'wordClass'), ('handedness', 'handedness'), ('handCh', 'handCh'), ('relatArtic', 'relatArtic'), ('locprim', 'locprim'), ('relOriMov', 'relOriMov'), ('relOriLoc', 'relOriLoc'), ('oriCh', 'oriCh'), ('contType', 'contType'), ('movSh', 'movSh'), ('movDir', 'movDir'), ('namEnt', 'namEnt'), ('valence', 'valence')], max_length=20, verbose_name='Field Name')),
                ('fieldValue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.FieldChoice')),
            ],
            bases=('dictionary.queryparameter',),
        ),
        migrations.CreateModel(
            name='QueryParameterHandshape',
            fields=[
                ('queryparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dictionary.QueryParameter')),
                ('fieldName', models.CharField(choices=[('domhndsh', 'domhndsh'), ('subhndsh', 'subhndsh')], max_length=20, verbose_name='Handshape')),
                ('fieldValue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Handshape')),
            ],
            bases=('dictionary.queryparameter',),
        ),
        migrations.CreateModel(
            name='QueryParameterSemanticField',
            fields=[
                ('queryparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dictionary.QueryParameter')),
                ('fieldName', models.CharField(choices=[('semField', 'semField')], max_length=20, verbose_name='Semantic Field')),
                ('fieldValue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.SemanticField')),
            ],
            bases=('dictionary.queryparameter',),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='parameters',
            field=models.ManyToManyField(to='dictionary.QueryParameter'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
