# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-02-03 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import signbank.dictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0056_auto_20230203_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryparameter',
            name='search_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.SearchHistory'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='parameters',
            field=models.ManyToManyField(related_name='query_paramters', to='dictionary.QueryParameter'),
        ),
    ]
