# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-02-09 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import signbank.dictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0057_auto_20230203_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryParameterBoolean',
            fields=[
                ('queryparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dictionary.QueryParameter')),
                ('fieldName', models.CharField(choices=[('weakdrop', 'weakdrop'), ('weakprop', 'weakprop'), ('domhndsh_letter', 'domhndsh_letter'), ('domhndsh_number', 'domhndsh_number'), ('subhndsh_letter', 'subhndsh_letter'), ('subhndsh_number', 'subhndsh_number'), ('repeat', 'repeat'), ('altern', 'altern'), ('inWeb', 'inWeb'), ('isNew', 'isNew'), ('oriChAbd', 'oriChAbd'), ('oriChFlex', 'oriChFlex')], max_length=20, verbose_name='NullBooleanField')),
                ('fieldValue', models.NullBooleanField(verbose_name='Field Value')),
            ],
            bases=('dictionary.queryparameter',),
        ),
        migrations.AlterField(
            model_name='queryparameterfieldchoice',
            name='fieldValue',
            field=models.ForeignKey(choices=[('wordClass', 'WordClass'), ('handedness', 'Handedness'), ('handCh', 'HandshapeChange'), ('relatArtic', 'RelatArtic'), ('locprim', 'Location'), ('relOriMov', 'RelOriMov'), ('relOriLoc', 'RelOriLoc'), ('oriCh', 'OriChange'), ('contType', 'ContactType'), ('movSh', 'MovementShape'), ('movDir', 'MovementDir'), ('namEnt', 'NamedEntity'), ('valence', 'Valence')], null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.FieldChoice', verbose_name='Field Value'),
        ),
        migrations.AlterField(
            model_name='queryparameterhandshape',
            name='fieldName',
            field=models.CharField(choices=[('domhndsh', 'domhndsh'), ('subhndsh', 'subhndsh'), ('final_domhndsh', 'final_domhndsh'), ('final_subhndsh', 'final_subhndsh')], max_length=20, verbose_name='Handshape'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='parameters',
            field=models.ManyToManyField(related_name='query_parameters', to='dictionary.QueryParameter'),
        ),
    ]
