# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-02-13 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import signbank.dictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0058_auto_20230209_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryParameterMultilingual',
            fields=[
                ('queryparameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dictionary.QueryParameter')),
                ('fieldName', models.CharField(choices=[('glosssearch', 'glosssearch'), ('lemma', 'lemma'), ('keyword', 'keyword')], max_length=20, verbose_name='Text Search Field')),
                ('fieldValue', models.CharField(max_length=30, verbose_name='Text Search Value')),
                ('fieldLanguage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Language')),
            ],
            bases=('dictionary.queryparameter',),
        ),
    ]
