# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-02-14 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import signbank.dictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0059_auto_20230213_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryparameterboolean',
            name='fieldName',
            field=models.CharField(choices=[('weakdrop', 'weakdrop'), ('weakprop', 'weakprop'), ('domhndsh_letter', 'domhndsh_letter'), ('domhndsh_number', 'domhndsh_number'), ('subhndsh_letter', 'subhndsh_letter'), ('subhndsh_number', 'subhndsh_number'), ('repeat', 'repeat'), ('altern', 'altern'), ('inWeb', 'inWeb'), ('isNew', 'isNew'), ('excludeFromEcv', 'excludeFromEcv'), ('oriChAbd', 'oriChAbd'), ('oriChFlex', 'oriChFlex'), ('hasRelationToForeignSign', 'hasRelationToForeignSign'), ('defspublished', 'defspublished'), ('hasvideo', 'hasvideo'), ('hasothermedia', 'hasothermedia')], max_length=20, verbose_name='NullBooleanField'),
        ),
    ]
