# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-02-16 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import signbank.dictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0060_auto_20230214_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queryparameterderivationhistory',
            options={'verbose_name_plural': 'Query parameter derivation histories'},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'verbose_name_plural': 'Search histories'},
        ),
        migrations.AlterField(
            model_name='queryparameterboolean',
            name='fieldName',
            field=models.CharField(choices=[('weakdrop', 'weakdrop'), ('weakprop', 'weakprop'), ('domhndsh_letter', 'domhndsh_letter'), ('domhndsh_number', 'domhndsh_number'), ('subhndsh_letter', 'subhndsh_letter'), ('subhndsh_number', 'subhndsh_number'), ('repeat', 'repeat'), ('altern', 'altern'), ('inWeb', 'inWeb'), ('isNew', 'isNew'), ('excludeFromEcv', 'excludeFromEcv'), ('oriChAbd', 'oriChAbd'), ('oriChFlex', 'oriChFlex'), ('hasRelationToForeignSign', 'hasRelationToForeignSign'), ('defspublished', 'defspublished'), ('hasvideo', 'hasvideo'), ('hasothermedia', 'hasothermedia')], max_length=30, verbose_name='NullBooleanField'),
        ),
        migrations.AlterField(
            model_name='queryparameterfieldchoice',
            name='fieldValue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.FieldChoice', verbose_name='Field Value'),
        ),
    ]
