# Generated by Django 4.1.4 on 2023-03-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0056_alter_dataset_options_and_more'),
        ('dictionary', '0061_auto_20230216_1540'),
    ]

    operations = [
    ]
