# Generated by Django 4.1.4 on 2023-03-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0062_merge_20230310_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gloss',
            options={'ordering': ['lemma'], 'permissions': (('update_video', 'Can Update Video'), ('search_gloss', 'Can Search/View Full Gloss Details'), ('export_csv', 'Can export sign details as CSV'), ('export_ecv', 'Can create an ECV export file of Signbank'), ('can_publish', 'Can publish signs and definitions'), ('can_delete_unpublished', 'Can delete unpub signs or defs'), ('can_delete_published', 'Can delete pub signs and defs'), ('view_advanced_properties', 'Include all properties in sign details')), 'verbose_name_plural': 'Glosses'},
        ),
        migrations.AlterField(
            model_name='gloss',
            name='concConcSet',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Concepticon Concept Set'),
        ),
        migrations.AlterField(
            model_name='queryparameterboolean',
            name='fieldValue',
            field=models.BooleanField(blank=True, null=True, verbose_name='Field Value'),
        ),
    ]
