# Generated by Django 4.1.7 on 2023-03-29 09:06

from django.db import migrations, models
import django.db.models.deletion
import signbank.dictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0063_alter_queryparameterfieldchoice_fieldname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='role',
            field=signbank.dictionary.models.FieldChoiceForeignKey(limit_choices_to={'field': 'NoteType'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='definition', to='dictionary.fieldchoice', verbose_name='Note Type'),
        ),
        migrations.AlterField(
            model_name='morphologydefinition',
            name='role',
            field=signbank.dictionary.models.FieldChoiceForeignKey(limit_choices_to={'field': 'MorphologyType'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.fieldchoice', verbose_name='Morphology Type'),
        ),
        migrations.AlterField(
            model_name='queryparameterfieldchoice',
            name='fieldName',
            field=models.CharField(choices=[('wordClass', 'wordClass'), ('handedness', 'handedness'), ('handCh', 'handCh'), ('relatArtic', 'relatArtic'), ('locprim', 'locprim'), ('relOriMov', 'relOriMov'), ('relOriLoc', 'relOriLoc'), ('oriCh', 'oriCh'), ('contType', 'contType'), ('movSh', 'movSh'), ('movDir', 'movDir'), ('namEnt', 'namEnt'), ('valence', 'valence'), ('definitionRole', 'definitionRole'), ('hasComponentOfType', 'hasComponentOfType')], max_length=20, verbose_name='Field Name'),
        ),
    ]
