# Generated by Django 4.1.7 on 2023-04-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0069_alter_queryparametermultilingual_fieldname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryparametermultilingual',
            name='fieldName',
            field=models.CharField(choices=[('glosssearch', 'glosssearch'), ('lemma', 'lemma'), ('keyword', 'keyword'), ('tags', 'tags'), ('definitionContains', 'definitionContains'), ('createdBy', 'createdBy'), ('translation', 'translation'), ('search', 'search'), ('createdBefore', 'createdBefore'), ('createdAfter', 'createdAfter')], max_length=20, verbose_name='Text Search Field'),
        ),
    ]
