# Generated by Django 4.1.7 on 2023-06-08 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0070_alter_queryparametermultilingual_fieldname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negative', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(default=5, help_text='Dataset an examplesentence is part of', null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.dataset', verbose_name='Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='translation',
            name='orderIndex',
            field=models.IntegerField(default=1, verbose_name='Sense Index'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='index',
            field=models.IntegerField(default=0, verbose_name='Index'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.language'),
        ),
        migrations.CreateModel(
            name='SenseTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.language')),
                ('translations', models.ManyToManyField(to='dictionary.translation')),
            ],
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderindex', models.IntegerField(default=0)),
                ('dataset', models.ForeignKey(default=5, help_text='Dataset a sense is part of', null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.dataset', verbose_name='Dataset')),
                ('exampleSentences', models.ManyToManyField(to='dictionary.examplesentence')),
                ('senseTranslations', models.ManyToManyField(to='dictionary.sensetranslation')),
            ],
            options={
                'ordering': ['orderindex'],
            },
        ),
        migrations.CreateModel(
            name='ExampleSentenceTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('examplesentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.examplesentence')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.language')),
            ],
        ),
        migrations.AddField(
            model_name='examplesentence',
            name='sentencetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.sentencetype'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='senses',
            field=models.ManyToManyField(to='dictionary.sense'),
        ),
    ]
