# Generated by Django 4.1.7 on 2023-05-08 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0070_alter_queryparametermultilingual_fieldname'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='orderIndex',
            field=models.IntegerField(default=1, verbose_name='Sense Index'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.language'),
        ),
    ]
