# Generated by Django 4.1.7 on 2023-06-08 13:19

from django.db import migrations, models
import django.db.models.deletion
import signbank.dictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0071_translation_orderindex_alter_translation_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negative', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(default=5, help_text='Dataset an examplesentence is part of', null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.dataset', verbose_name='Dataset')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='fieldchoice',
            name='field',
            field=models.CharField(choices=[('AbsOriFing', 'AbsOriFing'), ('AbsOriPalm', 'AbsOriPalm'), ('Aperture', 'Aperture'), ('ContactType', 'ContactType'), ('DominantHandFlexion', 'DominantHandFlexion'), ('DominantHandSelectedFingers', 'DominantHandSelectedFingers'), ('FingerSelection', 'FingerSelection'), ('Handedness', 'Handedness'), ('iconicity', 'iconicity'), ('HandshapeChange', 'HandshapeChange'), ('JointConfiguration', 'JointConfiguration'), ('Location', 'Location'), ('MinorLocation', 'MinorLocation'), ('MorphemeType', 'MorphemeType'), ('MorphologyType', 'MorphologyType'), ('MovementDir', 'MovementDir'), ('MovementMan', 'MovementMan'), ('MovementShape', 'MovementShape'), ('NamedEntity', 'NamedEntity'), ('NoteType', 'NoteType'), ('OriChange', 'OriChange'), ('OtherMediaType', 'OtherMediaType'), ('PathOnPath', 'PathOnPath'), ('Quantity', 'Quantity'), ('RelOriLoc', 'RelOriLoc'), ('RelOriMov', 'RelOriMov'), ('RelatArtic', 'RelatArtic'), ('Spreading', 'Spreading'), ('Thumb', 'Thumb'), ('Valence', 'Valence'), ('WordClass', 'WordClass'), ('SentenceType', 'SentenceType')], max_length=50),
        ),
        migrations.AlterField(
            model_name='queryparameterfieldchoice',
            name='fieldName',
            field=models.CharField(choices=[('wordClass', 'wordClass'), ('handedness', 'handedness'), ('handCh', 'handCh'), ('relatArtic', 'relatArtic'), ('locprim', 'locprim'), ('relOriMov', 'relOriMov'), ('relOriLoc', 'relOriLoc'), ('oriCh', 'oriCh'), ('contType', 'contType'), ('movSh', 'movSh'), ('movDir', 'movDir'), ('namEnt', 'namEnt'), ('valence', 'valence'), ('definitionRole', 'definitionRole'), ('hasComponentOfType', 'hasComponentOfType'), ('sentenceType', 'sentenceType')], max_length=20, verbose_name='Field Name'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='index',
            field=models.IntegerField(default=0, verbose_name='Index'),
        ),
        migrations.CreateModel(
            name='SenseTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.language')),
                ('translations', models.ManyToManyField(to='dictionary.translation')),
            ],
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderindex', models.IntegerField(default=0)),
                ('dataset', models.ForeignKey(default=5, help_text='Dataset a sense is part of', null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.dataset', verbose_name='Dataset')),
                ('exampleSentences', models.ManyToManyField(to='dictionary.examplesentence')),
                ('senseTranslations', models.ManyToManyField(to='dictionary.sensetranslation')),
            ],
            options={
                'ordering': ['orderindex'],
            },
        ),
        migrations.CreateModel(
            name='ExampleSentenceTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('examplesentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.examplesentence')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.language')),
            ],
        ),
        migrations.AddField(
            model_name='examplesentence',
            name='sentenceType',
            field=signbank.dictionary.models.FieldChoiceForeignKey(limit_choices_to={'field': 'SentenceType'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentence_type', to='dictionary.fieldchoice', verbose_name='Sentence Type'),
        ),
        migrations.AddField(
            model_name='gloss',
            name='senses',
            field=models.ManyToManyField(to='dictionary.sense'),
        ),
    ]
