# Generated by Django 4.1.7 on 2023-08-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0074_alter_translation_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryparameterboolean',
            name='fieldName',
            field=models.CharField(choices=[('weakdrop', 'weakdrop'), ('weakprop', 'weakprop'), ('domhndsh_letter', 'domhndsh_letter'), ('domhndsh_number', 'domhndsh_number'), ('subhndsh_letter', 'subhndsh_letter'), ('subhndsh_number', 'subhndsh_number'), ('repeat', 'repeat'), ('altern', 'altern'), ('inWeb', 'inWeb'), ('isNew', 'isNew'), ('excludeFromEcv', 'excludeFromEcv'), ('oriChAbd', 'oriChAbd'), ('oriChFlex', 'oriChFlex'), ('hasRelationToForeignSign', 'hasRelationToForeignSign'), ('defspublished', 'defspublished'), ('hasmultiplesenses', 'hasmultiplesenses'), ('hasvideo', 'hasvideo'), ('hasothermedia', 'hasothermedia')], max_length=30, verbose_name='NullBooleanField'),
        ),
    ]
