# Generated by Django 4.1.7 on 2023-08-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0076_senseexamplesentence_alter_sense_examplesentences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='senseexamplesentence',
            options={'ordering': ['order'], 'verbose_name': 'Sense exampleSentence', 'verbose_name_plural': 'Sense exampleSentences'},
        ),
        migrations.AddField(
            model_name='senseexamplesentence',
            name='order',
            field=models.IntegerField(default=1, help_text='What order to display this examplesentence within the sense.', verbose_name='Order'),
        ),
    ]
