# Generated by Django 3.2.25 on 2024-03-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0078_alter_queryparameterboolean_fieldname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['-id']},
        ),
    ]
