# Generated by Django 3.2.25 on 2024-03-21 10:21

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0079_alter_language_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('acronym', models.CharField(blank=True, help_text='Abbreviation for the affiliation', max_length=10)),
                ('field_color', colorfield.fields.ColorField(default='64cf00', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='SignbankToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signbank_token', models.CharField(blank=True, max_length=16, null=True, verbose_name='Token')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('signbank_dataset', models.ForeignKey(help_text='API Token to change Dataset', null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.dataset', verbose_name='Dataset')),
                ('signbank_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Signbank User')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.CreateModel(
            name='AffiliatedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.affiliation', verbose_name='Affiliation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_is_affiliated_with', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='AffiliatedGloss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.affiliation', verbose_name='Affiliation')),
                ('gloss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_corpus_contains', to='dictionary.gloss', verbose_name='Gloss')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='api_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authentication_token', to='dictionary.signbanktoken', verbose_name='API Token'),
        ),
    ]
