# Generated by Django 4.2.10 on 2024-04-24 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0080_auto_20240321_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotatedSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotatedSentenceTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('annotatedsentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotated_sentence_translations', to='dictionary.annotatedsentence')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.language')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotatedSentenceContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('annotatedsentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotated_sentence_contexts', to='dictionary.annotatedsentence')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.language')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotatedGloss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isRepresentative', models.BooleanField(default=False)),
                ('starttime', models.FloatField()),
                ('endtime', models.FloatField()),
                ('annotatedsentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotated_glosses', to='dictionary.annotatedsentence')),
                ('gloss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.gloss')),
            ],
        ),
    ]
