# Generated by Django 4.2.11 on 2024-07-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0083_annotatedsentencesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='gloss',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
