# Generated by Django 4.2.10 on 2024-11-29 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0086_alter_dataset_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('lemmas', models.TextField(blank=True, verbose_name='Lemmas')),
                ('url', models.TextField(blank=True, verbose_name='Url')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.dataset', verbose_name='Dataset')),
                ('glosses', models.ManyToManyField(related_name='synsets', to='dictionary.gloss', verbose_name='Glosses')),
            ],
        ),
    ]
