# Generated by Django 4.2.17 on 2025-03-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0087_synset'),
    ]

    operations = [
        migrations.AddField(
            model_name='gloss',
            name='release_label',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
