# Generated by Django 4.2.25 on 2025-11-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0093_add_entymology_to_other_media_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloss',
            name='release_information',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Release information'),
        ),
    ]
