# Generated by Django 4.2.27 on 2026-02-10 14:15

from django.db import migrations, models
import django.db.models.deletion
import signbank.dictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0094_alter_gloss_release_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='role_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(limit_choices_to={'field': 'RelationRole'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relation_role', to='dictionary.fieldchoice', verbose_name='Relation Role'),
        ),
        migrations.AlterField(
            model_name='fieldchoice',
            name='field',
            field=models.CharField(choices=[('AbsOriFing', 'AbsOriFing'), ('AbsOriPalm', 'AbsOriPalm'), ('Aperture', 'Aperture'), ('ContactType', 'ContactType'), ('DominantHandFlexion', 'DominantHandFlexion'), ('DominantHandSelectedFingers', 'DominantHandSelectedFingers'), ('FingerSelection', 'FingerSelection'), ('Handedness', 'Handedness'), ('HandshapeChange', 'HandshapeChange'), ('iconicity', 'iconicity'), ('JointConfiguration', 'JointConfiguration'), ('Location', 'Location'), ('MinorLocation', 'MinorLocation'), ('MorphemeType', 'MorphemeType'), ('MorphologyType', 'MorphologyType'), ('MovementDir', 'MovementDir'), ('MovementMan', 'MovementMan'), ('MovementShape', 'MovementShape'), ('NamedEntity', 'NamedEntity'), ('NoteType', 'NoteType'), ('OriChange', 'OriChange'), ('OtherMediaType', 'OtherMediaType'), ('PathOnPath', 'PathOnPath'), ('Provenance', 'Provenance'), ('Quantity', 'Quantity'), ('RelatArtic', 'RelatArtic'), ('RelationRole', 'RelationRole'), ('RelOriLoc', 'RelOriLoc'), ('RelOriMov', 'RelOriMov'), ('SentenceType', 'SentenceType'), ('Spreading', 'Spreading'), ('Thumb', 'Thumb'), ('Valence', 'Valence'), ('WordClass', 'WordClass')], max_length=50),
        ),
    ]
