# Generated by Django 4.2.28 on 2026-03-04 12:23

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0094_alter_gloss_release_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='field_color',
            field=colorfield.fields.ColorField(default='64cf00', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='derivationhistory',
            name='field_color',
            field=colorfield.fields.ColorField(default='ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='fieldchoice',
            name='field_color',
            field=colorfield.fields.ColorField(default='ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='handshape',
            name='field_color',
            field=colorfield.fields.ColorField(default='ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='semanticfield',
            name='field_color',
            field=colorfield.fields.ColorField(default='ffffff', image_field=None, max_length=25, samples=None),
        ),
    ]
