# Generated by Django 4.2.28 on 2026-03-11 13:31

from django.db import migrations, models
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from signbank.settings.server_specific import MODELTRANSLATION_LANGUAGES


def add_reverse_relation_roles(apps, schema_editor):
    """
    Add predefined reverse relation roles for category RelationRole
    :param apps:
    :param schema_editor:
    :return:
    """
    FieldChoice = apps.get_model('dictionary', 'FieldChoice')

    def has_name(fieldchoice, name):
        name_fields = [f'name_{language.replace('-', '_')}' for language in MODELTRANSLATION_LANGUAGES]
        matches = any(getattr(fieldchoice, name_field) == name for name_field in name_fields)
        return matches

    def lookup(name):
        q = Q()
        for language in MODELTRANSLATION_LANGUAGES:
            field_name = 'name_' + language.replace('-', '_')
            q |= Q(**{f"{field_name}__iexact": name})
        return FieldChoice.objects.filter(field='RelationRole').filter(q).distinct().get()

    for fieldchoice_relation_role in FieldChoice.objects.filter(field='RelationRole', machine_value__gt=1):
        if has_name(fieldchoice_relation_role, 'Hyponym'):
            try:
                hypernym = lookup("Hypernym")
                fieldchoice_relation_role.reverse = hypernym
            except (ObjectDoesNotExist, MultipleObjectsReturned):
                fieldchoice_relation_role.reverse = fieldchoice_relation_role
        elif has_name(fieldchoice_relation_role, 'Hypernym'):
            try:
                hyponym = lookup("Hyponym")
                fieldchoice_relation_role.reverse = hyponym
            except (ObjectDoesNotExist, MultipleObjectsReturned):
                fieldchoice_relation_role.reverse = fieldchoice_relation_role
        else:
            fieldchoice_relation_role.reverse = fieldchoice_relation_role
        fieldchoice_relation_role.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0096_fieldchoice_reverse'),
    ]

    operations = [
        migrations.RunPython(add_reverse_relation_roles),
    ]
