# Generated by Django 4.2.28 on 2026-03-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0095_relation_role_populate'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldchoice',
            name='reverse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.fieldchoice', verbose_name='Reverse Relation'),
        ),
    ]
