# Generated by Django 4.2.30 on 2026-06-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0096_fieldchoice_reverse_populate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='use_lookaheads',
            field=models.BooleanField(default=False, verbose_name='Use Lookaheads'),
        ),
    ]
