# Generated by Django 4.2.30 on 2026-04-20 11:26

from django.db import migrations, models
import django.db.models.deletion
import signbank.dictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0096_fieldchoice_reverse_populate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonologicalVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.IntegerField(default=0)),
                ('weakdrop', models.BooleanField(blank=True, null=True, verbose_name='Weak Drop')),
                ('weakprop', models.BooleanField(blank=True, null=True, verbose_name='Weak Prop')),
                ('domhndsh_number', models.BooleanField(blank=True, null=True, verbose_name='Strong hand number')),
                ('domhndsh_letter', models.BooleanField(blank=True, null=True, verbose_name='Strong hand letter')),
                ('subhndsh_number', models.BooleanField(blank=True, null=True, verbose_name='Weak hand number')),
                ('subhndsh_letter', models.BooleanField(blank=True, null=True, verbose_name='Weak hand letter')),
                ('locVirtObj', models.CharField(blank=True, max_length=50, null=True, verbose_name='Virtual Object')),
                ('initial_palm_orientation', models.CharField(blank=True, max_length=20, null=True, verbose_name='Initial Palm Orientation')),
                ('final_palm_orientation', models.CharField(blank=True, max_length=20, null=True, verbose_name='Final Palm Orientation')),
                ('initial_relative_orientation', models.CharField(blank=True, max_length=20, null=True, verbose_name='Initial Interacting Dominant Hand Part')),
                ('final_relative_orientation', models.CharField(blank=True, max_length=20, null=True, verbose_name='Final Interacting Dominant Hand Part')),
                ('oriChAbd', models.BooleanField(blank=True, null=True, verbose_name='Abduction change')),
                ('oriChFlex', models.BooleanField(blank=True, null=True, verbose_name='Flexion change')),
                ('domFlex', signbank.dictionary.models.FieldChoiceForeignKey(limit_choices_to={'field': 'DominantHandFlexion'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_dominant_hand_flexion', to='dictionary.fieldchoice', verbose_name='Dominant hand - Flexion')),
                ('domSF', signbank.dictionary.models.FieldChoiceForeignKey(limit_choices_to={'field': 'DominantHandSelectedFingers'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_dominant_hand_selected_fingers', to='dictionary.fieldchoice', verbose_name='Dominant hand - Selected Fingers')),
                ('domhndsh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_strong_hand', to='dictionary.handshape', verbose_name='Strong Hand')),
                ('final_domhndsh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_final_dominant_handshape', to='dictionary.handshape', verbose_name='Final Dominant Handshape')),
                ('final_loc', signbank.dictionary.models.FieldChoiceForeignKey(limit_choices_to={'field': 'Location'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_final_primary_location', to='dictionary.fieldchoice', verbose_name='Final Primary Location')),
                ('final_secondary_loc', signbank.dictionary.models.FieldChoiceForeignKey(limit_choices_to={'field': 'MinorLocation'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_final_subordinate_location', to='dictionary.fieldchoice', verbose_name='Final Subordinate Location')),
                ('final_subhndsh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_final_subordinate_handshape', to='dictionary.handshape', verbose_name='Final Subordinate Handshape')),
                ('gloss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.gloss')),
                ('handedness', signbank.dictionary.models.FieldChoiceForeignKey(limit_choices_to={'field': 'Handedness'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_handedness', to='dictionary.fieldchoice', verbose_name='Handedness')),
                ('initial_secondary_loc', signbank.dictionary.models.FieldChoiceForeignKey(limit_choices_to={'field': 'MinorLocation'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_initial_subordinate_location', to='dictionary.fieldchoice', verbose_name='Initial Subordinate Location')),
                ('locprim', signbank.dictionary.models.FieldChoiceForeignKey(limit_choices_to={'field': 'Location'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_location', to='dictionary.fieldchoice', verbose_name='Location')),
                ('locsecond', signbank.dictionary.models.FieldChoiceForeignKey(limit_choices_to={'field': 'Location'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_secondary_location', to='dictionary.fieldchoice', verbose_name='Secondary Location')),
                ('subhndsh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_weak_hand', to='dictionary.handshape', verbose_name='Weak Hand')),
            ],
            options={
                'ordering': ['gloss', 'variation'],
                'unique_together': {('gloss', 'variation')},
            },
        ),
    ]
