# Generated by Django 4.2.30 on 2026-04-29 10:07

from django.db import migrations, models
import django.db.models.deletion
import signbank.dictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0096_fieldchoice_reverse_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloss',
            name='absOriFing',
            field=signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'AbsOriFing'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_absolute_orientation_fingers', to='dictionary.fieldchoice', verbose_name='Absolute Orientation: Fingers'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='absOriPalm',
            field=signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'AbsOriPalm'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_absolute_orientation_palm', to='dictionary.fieldchoice', verbose_name='Absolute Orientation: Palm'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='contType',
            field=signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'ContactType'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_contact_type', to='dictionary.fieldchoice', verbose_name='Contact Type'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='domFlex',
            field=signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'DominantHandFlexion'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_dominant_hand_flexion', to='dictionary.fieldchoice', verbose_name='Dominant hand - Flexion'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='domSF',
            field=signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'DominantHandSelectedFingers'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_dominant_hand_selected_fingers', to='dictionary.fieldchoice', verbose_name='Dominant hand - Selected Fingers'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='domhndsh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_strong_hand', to='dictionary.handshape', verbose_name='Strong Hand'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='final_domhndsh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_final_dominant_handshape', to='dictionary.handshape', verbose_name='Final Dominant Handshape'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='final_loc',
            field=signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'Location'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_final_primary_location', to='dictionary.fieldchoice', verbose_name='Final Primary Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='final_secondary_loc',
            field=signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'MinorLocation'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_final_subordinate_location', to='dictionary.fieldchoice', verbose_name='Final Subordinate Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='final_subhndsh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_final_subordinate_handshape', to='dictionary.handshape', verbose_name='Final Subordinate Handshape'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='handCh',
            field=signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'HandshapeChange'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_handshape_change', to='dictionary.fieldchoice', verbose_name='Handshape Change'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='handedness',
            field=signbank.dictionary.models.FieldChoiceForeignKey(limit_choices_to={'field': 'Handedness'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_handedness', to='dictionary.fieldchoice', verbose_name='Handedness'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='initial_secondary_loc',
            field=signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'MinorLocation'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_initial_subordinate_location', to='dictionary.fieldchoice', verbose_name='Initial Subordinate Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='locPrimLH',
            field=signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'Location'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_placement_active_articulator_lh', to='dictionary.fieldchoice', verbose_name='Placement Active Articulator LH'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='locprim',
            field=signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'Location'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_location', to='dictionary.fieldchoice', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='locsecond',
            field=signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'Location'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_secondary_location', to='dictionary.fieldchoice', verbose_name='Secondary Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='movDir',
            field=signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'MovementDir'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_movement_direction', to='dictionary.fieldchoice', verbose_name='Movement Direction'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='movMan',
            field=signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'MovementMan'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_movement_manner', to='dictionary.fieldchoice', verbose_name='Movement Manner'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='movSh',
            field=signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'MovementShape'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_movement_shape', to='dictionary.fieldchoice', verbose_name='Movement Shape'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='oriCh',
            field=signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'OriChange'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_orientation_change', to='dictionary.fieldchoice', verbose_name='Orientation Change'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='relOriLoc',
            field=signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'RelOriLoc'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_relative_orientation_location', to='dictionary.fieldchoice', verbose_name='Relative Orientation: Location'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='relOriMov',
            field=signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'RelOriMov'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_relative_orientation_movement', to='dictionary.fieldchoice', verbose_name='Relative Orientation: Movement'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='relatArtic',
            field=signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'RelatArtic'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_relation_between_articulators', to='dictionary.fieldchoice', verbose_name='Relation between Articulators'),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='subhndsh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_weak_hand', to='dictionary.handshape', verbose_name='Weak Hand'),
        ),
        migrations.CreateModel(
            name='PhonologicalVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weakdrop', models.BooleanField(blank=True, null=True, verbose_name='Weak Drop')),
                ('weakprop', models.BooleanField(blank=True, null=True, verbose_name='Weak Prop')),
                ('domhndsh_number', models.BooleanField(blank=True, null=True, verbose_name='Strong hand number')),
                ('domhndsh_letter', models.BooleanField(blank=True, null=True, verbose_name='Strong hand letter')),
                ('subhndsh_number', models.BooleanField(blank=True, null=True, verbose_name='Weak hand number')),
                ('subhndsh_letter', models.BooleanField(blank=True, null=True, verbose_name='Weak hand letter')),
                ('locVirtObj', models.CharField(blank=True, max_length=50, null=True, verbose_name='Virtual Object')),
                ('initial_palm_orientation', models.CharField(blank=True, max_length=20, null=True, verbose_name='Initial Palm Orientation')),
                ('final_palm_orientation', models.CharField(blank=True, max_length=20, null=True, verbose_name='Final Palm Orientation')),
                ('initial_relative_orientation', models.CharField(blank=True, max_length=20, null=True, verbose_name='Initial Interacting Dominant Hand Part')),
                ('final_relative_orientation', models.CharField(blank=True, max_length=20, null=True, verbose_name='Final Interacting Dominant Hand Part')),
                ('oriChAbd', models.BooleanField(blank=True, null=True, verbose_name='Abduction change')),
                ('oriChFlex', models.BooleanField(blank=True, null=True, verbose_name='Flexion change')),
                ('repeat', models.BooleanField(default=False, null=True, verbose_name='Repeated Movement')),
                ('altern', models.BooleanField(default=False, null=True, verbose_name='Alternating Movement')),
                ('phonOth', models.TextField(blank=True, null=True, verbose_name='Phonology Other')),
                ('mouthG', models.CharField(blank=True, max_length=50, verbose_name='Mouth Gesture')),
                ('mouthing', models.CharField(blank=True, max_length=50, verbose_name='Mouthing')),
                ('phonetVar', models.CharField(blank=True, max_length=50, verbose_name='Phonetic Variation')),
                ('locFocSite', models.CharField(blank=True, max_length=5, null=True, verbose_name='Placement Focal Site RH')),
                ('locFocSiteLH', models.CharField(blank=True, max_length=5, null=True, verbose_name='Placement Focal site LH')),
                ('initArtOri', models.CharField(blank=True, max_length=5, null=True, verbose_name='Orientation RH (initial)')),
                ('finArtOri', models.CharField(blank=True, max_length=5, null=True, verbose_name='Orientation RH (final)')),
                ('initArtOriLH', models.CharField(blank=True, max_length=5, null=True, verbose_name='Orientation LH (initial)')),
                ('finArtOriLH', models.CharField(blank=True, max_length=5, null=True, verbose_name='Orientation LH (final)')),
                ('variation', models.IntegerField(default=0)),
                ('absOriFing', signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'AbsOriFing'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_absolute_orientation_fingers', to='dictionary.fieldchoice', verbose_name='Absolute Orientation: Fingers')),
                ('absOriPalm', signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'AbsOriPalm'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_absolute_orientation_palm', to='dictionary.fieldchoice', verbose_name='Absolute Orientation: Palm')),
                ('contType', signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'ContactType'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_contact_type', to='dictionary.fieldchoice', verbose_name='Contact Type')),
                ('domFlex', signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'DominantHandFlexion'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_dominant_hand_flexion', to='dictionary.fieldchoice', verbose_name='Dominant hand - Flexion')),
                ('domSF', signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'DominantHandSelectedFingers'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_dominant_hand_selected_fingers', to='dictionary.fieldchoice', verbose_name='Dominant hand - Selected Fingers')),
                ('domhndsh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_strong_hand', to='dictionary.handshape', verbose_name='Strong Hand')),
                ('final_domhndsh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_final_dominant_handshape', to='dictionary.handshape', verbose_name='Final Dominant Handshape')),
                ('final_loc', signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'Location'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_final_primary_location', to='dictionary.fieldchoice', verbose_name='Final Primary Location')),
                ('final_secondary_loc', signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'MinorLocation'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_final_subordinate_location', to='dictionary.fieldchoice', verbose_name='Final Subordinate Location')),
                ('final_subhndsh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_final_subordinate_handshape', to='dictionary.handshape', verbose_name='Final Subordinate Handshape')),
                ('gloss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.gloss')),
                ('handCh', signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'HandshapeChange'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_handshape_change', to='dictionary.fieldchoice', verbose_name='Handshape Change')),
                ('handedness', signbank.dictionary.models.FieldChoiceForeignKey(limit_choices_to={'field': 'Handedness'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_handedness', to='dictionary.fieldchoice', verbose_name='Handedness')),
                ('initial_secondary_loc', signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'MinorLocation'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_initial_subordinate_location', to='dictionary.fieldchoice', verbose_name='Initial Subordinate Location')),
                ('locPrimLH', signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'Location'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_placement_active_articulator_lh', to='dictionary.fieldchoice', verbose_name='Placement Active Articulator LH')),
                ('locprim', signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'Location'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_location', to='dictionary.fieldchoice', verbose_name='Location')),
                ('locsecond', signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'Location'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_secondary_location', to='dictionary.fieldchoice', verbose_name='Secondary Location')),
                ('movDir', signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'MovementDir'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_movement_direction', to='dictionary.fieldchoice', verbose_name='Movement Direction')),
                ('movMan', signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'MovementMan'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_movement_manner', to='dictionary.fieldchoice', verbose_name='Movement Manner')),
                ('movSh', signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'MovementShape'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_movement_shape', to='dictionary.fieldchoice', verbose_name='Movement Shape')),
                ('oriCh', signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'OriChange'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_orientation_change', to='dictionary.fieldchoice', verbose_name='Orientation Change')),
                ('relOriLoc', signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'RelOriLoc'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_relative_orientation_location', to='dictionary.fieldchoice', verbose_name='Relative Orientation: Location')),
                ('relOriMov', signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'RelOriMov'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_relative_orientation_movement', to='dictionary.fieldchoice', verbose_name='Relative Orientation: Movement')),
                ('relatArtic', signbank.dictionary.models.FieldChoiceForeignKey(blank=True, limit_choices_to={'field': 'RelatArtic'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_relation_between_articulators', to='dictionary.fieldchoice', verbose_name='Relation between Articulators')),
                ('subhndsh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_weak_hand', to='dictionary.handshape', verbose_name='Weak Hand')),
            ],
            options={
                'ordering': ['gloss', 'variation'],
                'unique_together': {('gloss', 'variation')},
            },
            bases=(signbank.dictionary.models.MetaModelMixin, models.Model),
        ),
    ]
