# Generated by Django 5.2 on 2026-09-16 06:57

from django.db import migrations
from signbank.dictionary.migration_tools import sql_for_app_removal


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0097_alter_gloss_absorifing_alter_gloss_absoripalm_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=sql_for_app_removal('reversion', ['reversion_revision', 'reversion_version']),
        ),
    ]
