# Generated by Django 5.2 on 2026-09-16 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0097_alter_gloss_absorifing_alter_gloss_absoripalm_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE reversion_version;",
        ),
        migrations.RunSQL(
            sql="DROP TABLE reversion_revision;",
        ),
    ]
