# Generated by Django 4.2.30 on 2026-09-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0098_drop_reversion_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='gloss',
            name='trigger',
            field=models.TextField(blank=True, null=True, verbose_name='Trigger'),
        ),
    ]
