# Generated by Django 4.2.29 on 2026-09-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0098_drop_reversion_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signbankapitoken',
            options={'ordering': ['-created'], 'verbose_name': 'API Token', 'verbose_name_plural': 'API Tokens'},
        ),
        migrations.AddField(
            model_name='signbankapitoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Leave empty for a token that does not expire', null=True, verbose_name='Expires'),
        ),
        migrations.AddField(
            model_name='signbankapitoken',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive tokens are rejected by the API', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='signbankapitoken',
            name='last_used_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last used'),
        ),
        migrations.AddField(
            model_name='signbankapitoken',
            name='name',
            field=models.CharField(blank=True, help_text='A label to recognise the token by, e.g. the script or machine using it', max_length=100, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='signbankapitoken',
            name='prefix',
            field=models.CharField(blank=True, editable=False, help_text='The first characters of the token, to help identify it', max_length=8, verbose_name='Prefix'),
        ),
        migrations.AddField(
            model_name='signbankapitoken',
            name='rate_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of requests per hour. Leave empty to use the site default.', null=True, verbose_name='Rate limit'),
        ),
        migrations.AddField(
            model_name='signbankapitoken',
            name='read_only',
            field=models.BooleanField(default=False, help_text='Read only tokens can only be used for GET requests', verbose_name='Read only'),
        ),
        migrations.AlterField(
            model_name='signbankapitoken',
            name='api_token',
            field=models.CharField(db_index=True, editable=False, max_length=64, verbose_name='Token'),
        ),
    ]
