# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=100, verbose_name='URL')),
                ('title', models.CharField(max_length=200, verbose_name='English title')),
                ('title_dutch', models.CharField(max_length=200, verbose_name='Dutch title')),
                ('title_chinese', models.CharField(max_length=200, verbose_name='Chinese title')),
                ('content', models.TextField(blank=True, verbose_name='English content')),
                ('content_dutch', models.TextField(blank=True, verbose_name='Dutch content')),
                ('content_chinese', models.TextField(blank=True, verbose_name='Chinese content')),
                ('template_name', models.CharField(blank=True, help_text="Example: 'pages/contact_page.html'. If this isn't provided, the system will use 'pages/default.html'.", max_length=70, verbose_name='template name')),
                ('publish', models.BooleanField(default=False, help_text='If this is checked, the page will be included in the site menus.', verbose_name='publish')),
                ('index', models.IntegerField(default=0, help_text='Used to order pages in the menu', verbose_name='ordering index')),
                ('group_required', models.ManyToManyField(blank=True, help_text='This page will only be visible to members of these groups, leave blank to allow anyone to access.', to='auth.Group')),
                ('parent', models.ForeignKey(blank=True, help_text='Leave blank for a top level menu entry.  Top level entries that have sub-pages should be empty as they will not be linked in the menu.', null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Page')),
            ],
            options={
                'ordering': ('url', 'index'),
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
            },
        ),
        migrations.CreateModel(
            name='PageVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('number', models.PositiveIntegerField(verbose_name='number')),
                ('video', models.FileField(blank=True, upload_to=b'pages')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page')),
            ],
        ),
    ]
