# Generated by Django 4.1.7 on 2023-05-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20220630_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_ar',
            field=models.TextField(blank=True, null=True, verbose_name='English content'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='English content'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_he',
            field=models.TextField(blank=True, null=True, verbose_name='English content'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_nl',
            field=models.TextField(blank=True, null=True, verbose_name='English content'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='English content'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='English title'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='English title'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_he',
            field=models.CharField(max_length=200, null=True, verbose_name='English title'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_nl',
            field=models.CharField(max_length=200, null=True, verbose_name='English title'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_zh_hans',
            field=models.CharField(max_length=200, null=True, verbose_name='English title'),
        ),
    ]
