# Generated by Django 4.1.7 on 2023-05-24 09:49

from django.db import migrations
from django.db.models import F
from signbank.settings.server_specific import LANGUAGES


def copy_page_translated_field(apps, schema_editor):
    """
    Copy the translated fields 'title' and 'content' to the Model Translation fields
    """
    Page = apps.get_model('pages', 'Page')
    page_field_names = [field.name for field in Page._meta.get_fields()]
    for language in LANGUAGES:
        language_code = "_" + language[0].replace("-", "_")
        language_name = "_" + language[1].lower()

        # We assume that if language_name is not used in a field name,
        # it is the default language.
        if 'title'+language_name not in page_field_names:
            language_name = ''

        old_field_name_title = 'title' + language_name
        old_field_name_content = 'content' + language_name

        new_field_name_title = 'title' + language_code
        new_field_name_content = 'content' + language_code

        Page.objects.update(**{new_field_name_title: F(old_field_name_title)},
                            **{new_field_name_content: F(old_field_name_content)})

        # for page in Page.objects.all():
        #     value_to_copy = getattr(page, old_field_name_title)
        #     setattr(page, new_field_name_title, value_to_copy)
        #     value_to_copy = getattr(page, old_field_name_content)
        #     setattr(page, new_field_name_content, value_to_copy)
        #     page.save()
            


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_content_ar_page_content_en_page_content_he_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_page_translated_field),
    ]
