# Generated by Django 4.1.7 on 2023-05-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20230524_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_he',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_nl',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_zh_hans',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
