# Generated by Django 4.1.7 on 2023-05-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_page_content_alter_page_content_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='content_arabic',
        ),
        migrations.RemoveField(
            model_name='page',
            name='content_chinese',
        ),
        migrations.RemoveField(
            model_name='page',
            name='content_dutch',
        ),
        migrations.RemoveField(
            model_name='page',
            name='content_hebrew',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title_arabic',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title_chinese',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title_dutch',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title_hebrew',
        ),
    ]
