# Generated by Django 4.2.20 on 2026-02-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_page_content_arabic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageVideo',
        ),
    ]
