from signbank.settings.server_specific.default import *
from signbank.settings.server_specific.server_specific import *

#These settings include parts of other settings, but this was hidden in the settings files imported above for convenience
BASE_DIR = ROOT+BASE_DIR
WRITABLE_FOLDER = ROOT+WRITABLE_FOLDER

OTHER_MEDIA_DIRECTORY = WRITABLE_FOLDER+OTHER_MEDIA_DIRECTORY
IMAGES_TO_IMPORT_FOLDER = WRITABLE_FOLDER+IMAGES_TO_IMPORT_FOLDER
VIDEOS_TO_IMPORT_FOLDER = WRITABLE_FOLDER+VIDEOS_TO_IMPORT_FOLDER
OTHER_MEDIA_TO_IMPORT_FOLDER = WRITABLE_FOLDER+OTHER_MEDIA_TO_IMPORT_FOLDER
SIGNBANK_PACKAGES_FOLDER = WRITABLE_FOLDER+SIGNBANK_PACKAGES_FOLDER
EAF_FILES_LOCATION = WRITABLE_FOLDER+EAF_FILES_LOCATION

METADATA_LOCATION = ROOT+METADATA_LOCATION

ECV_FOLDER = WRITABLE_FOLDER+ECV_FOLDER
ECV_FILE = ECV_FOLDER+ECV_FILE

if not SWITCH_TO_MYSQL:
    DATABASES['default']['NAME'] = WRITABLE_FOLDER + DATABASES['default']['NAME']
    DATABASES['default']['TEST']['NAME'] = WRITABLE_FOLDER + DATABASES['default']['TEST']['NAME']

print(DATABASES)

WSGI_FILE = ROOT+WSGI_FILE
