# Generated by Django 4.2.15 on 2024-09-23 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import signbank.animation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0086_alter_dataset_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossAnimationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('delete', 'delete'), ('upload', 'upload'), ('rename', 'rename'), ('watch', 'watch'), ('import', 'import')], default='watch', max_length=6, verbose_name='Animation History Action')),
                ('datestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of action')),
                ('uploadfile', models.TextField(default='(not specified)', verbose_name='User upload path')),
                ('goal_location', models.TextField(default='(not specified)', verbose_name='Full target path')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gloss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.gloss')),
            ],
            options={
                'ordering': ['datestamp'],
            },
        ),
        migrations.CreateModel(
            name='GlossAnimation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=signbank.animation.models.AnimationStorage(), upload_to='', validators=[signbank.animation.models.validate_file_extension], verbose_name='Animation file')),
                ('gloss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.gloss')),
            ],
        ),
    ]
