# Generated by Django 4.2.25 on 2025-11-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_auto_20170323_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Label without spaces', max_length=50, verbose_name='Description of type of communication')),
                ('subject', models.TextField(help_text='The communication text.', verbose_name='Site communication subject')),
                ('text', models.TextField(help_text='The communication text.', verbose_name='Site communication text')),
            ],
        ),
    ]
