# Generated by Django 4.2.26 on 2026-01-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_auto_20170323_1337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
