# Generated by Django 4.2.26 on 2026-01-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('-', 'Type of Communication'), ('activation_email', 'Mail to New User: Welcome to Signbank'), ('dataset_to_owner_existing_user_given_access', 'Mail to Dataset Owner: Existing User Given Access'), ('dataset_to_owner_new_user_given_access', 'Mail to Dataset Owner: New User Given Access'), ('dataset_to_owner_user_requested_access', 'Mail to Dataset Owner: User Requested Access'), ('dataset_to_user_existing_user_given_access', 'Mail to Existing User: Access Granted')], help_text='Label without spaces', max_length=50, verbose_name='Description of type of communication')),
                ('subject', models.TextField(help_text='The communication subject.', verbose_name='Site communication subject')),
                ('text', models.TextField(help_text='The communication text.', verbose_name='Site communication text')),
            ],
        ),
    ]
