# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 10:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('video', models.FileField(blank=True, upload_to=b'comments')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(b'unread', b'unread'), (b'read', b'read'), (b'deleted', b'deleted')], default=b'unread', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InterpreterFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name=b'Note')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(b'unread', b'unread'), (b'read', b'read'), (b'deleted', b'deleted')], default=b'unread', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'permissions': (('view_interpreterfeedback', 'Can View Interpreter Feedback'),),
            },
        ),
        migrations.CreateModel(
            name='MissingSignFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('handform', models.IntegerField(blank=True, choices=[(1, b'One handed'), (2, b'Two handed (same shape for each hand)'), (3, b'Two handed (diffent shapes for each hand)')], default=0)),
                ('handshape', models.IntegerField(blank=True, choices=[(0, b'None'), (291, b'Animal'), (292, b'Animal-flick'), (293, b'Bad'), (294, b'Ball'), (295, b'Cup'), (296, b'Cup-flush'), (297, b'Cup-thumb'), (298, b'Eight'), (299, b'Eight-hook'), (300, b'Fist-A'), (301, b'Fist-S'), (302, b'Flat'), (303, b'Flat-bent'), (304, b'Flat-B'), (305, b'Flat-flush'), (306, b'Flick'), (307, b'Flick-gay'), (308, b'Four'), (309, b'Five'), (310, b'Good'), (311, b'Good-6'), (312, b'Gun'), (313, b'Gun-hook'), (314, b'Hook'), (315, b'Kneel'), (316, b'Letter-C'), (317, b'Letter-M'), (318, b'Letter-N'), (319, b'Love'), (320, b'Middle'), (321, b'Mother'), (322, b'Nine'), (323, b'Point-1'), (324, b'Point-D'), (325, b'Point-flush'), (326, b'Okay-flat'), (327, b'Okay-F'), (328, b'Okay-O'), (329, b'Old-seven'), (330, b'Plane'), (331, b'Perth'), (332, b'Round-O'), (333, b'Round-flat'), (334, b'Round-E'), (335, b'Rude'), (336, b'Salt'), (337, b'Salt-flick'), (338, b'Small'), (339, b'Soon'), (340, b'Spoon'), (341, b'Spoon-hook'), (342, b'Spoon-thumb'), (343, b'Thick'), (344, b'Three'), (345, b'Three-hook'), (346, b'Two'), (347, b'Wish'), (348, b'Write'), (349, b'Write-flat')], default=0)),
                ('althandshape', models.IntegerField(blank=True, choices=[(0, b'None'), (291, b'Animal'), (292, b'Animal-flick'), (293, b'Bad'), (294, b'Ball'), (295, b'Cup'), (296, b'Cup-flush'), (297, b'Cup-thumb'), (298, b'Eight'), (299, b'Eight-hook'), (300, b'Fist-A'), (301, b'Fist-S'), (302, b'Flat'), (303, b'Flat-bent'), (304, b'Flat-B'), (305, b'Flat-flush'), (306, b'Flick'), (307, b'Flick-gay'), (308, b'Four'), (309, b'Five'), (310, b'Good'), (311, b'Good-6'), (312, b'Gun'), (313, b'Gun-hook'), (314, b'Hook'), (315, b'Kneel'), (316, b'Letter-C'), (317, b'Letter-M'), (318, b'Letter-N'), (319, b'Love'), (320, b'Middle'), (321, b'Mother'), (322, b'Nine'), (323, b'Point-1'), (324, b'Point-D'), (325, b'Point-flush'), (326, b'Okay-flat'), (327, b'Okay-F'), (328, b'Okay-O'), (329, b'Old-seven'), (330, b'Plane'), (331, b'Perth'), (332, b'Round-O'), (333, b'Round-flat'), (334, b'Round-E'), (335, b'Rude'), (336, b'Salt'), (337, b'Salt-flick'), (338, b'Small'), (339, b'Soon'), (340, b'Spoon'), (341, b'Spoon-hook'), (342, b'Spoon-thumb'), (343, b'Thick'), (344, b'Three'), (345, b'Three-hook'), (346, b'Two'), (347, b'Wish'), (348, b'Write'), (349, b'Write-flat')], default=0)),
                ('location', models.IntegerField(blank=True, choices=[(0, b'None'), (257, b'Top of head'), (258, b'Forehead'), (259, b'Temple'), (260, b'Eyes'), (261, b'Nose'), (262, b'Whole of face'), (263, b'Cheekbone'), (264, b'Ear'), (265, b'Cheek'), (266, b'Mouth and lips'), (267, b'Chin'), (268, b'Neck'), (269, b'Shoulder'), (270, b'Chest'), (271, b'Stomach'), (272, b'Waist'), (273, b'Lower waist'), (274, b'Upper arm'), (275, b'Elbow')], default=0)),
                ('relativelocation', models.IntegerField(blank=True, choices=[(0, b'None'), (283, b'Forearm'), (284, b'Wrist'), (285, b'Pulse'), (286, b'Back of hand'), (287, b'Palm'), (288, b'Sides of hand'), (289, b'Fingertips')], default=0)),
                ('handbodycontact', models.IntegerField(blank=True, choices=[(0, b'None'), (240, b'Contact at start of movement'), (241, b'Contact at end of movement'), (242, b'Two contacts (tap)'), (243, b'Contact during (rub/stroke)')], default=0)),
                ('handinteraction', models.IntegerField(blank=True, choices=[(0, b'None'), (468, b'Alternate hands (one moves, then the other moves)'), (469, b'Move the hands towards each other'), (470, b'Move the hands away from each other'), (471, b'The hands cross over each other')], default=0)),
                ('direction', models.IntegerField(blank=True, choices=[(0, b'None'), (472, b'Up'), (473, b'Down'), (474, b'Up and down'), (475, b'Left'), (476, b'Right'), (477, b'Side to side'), (478, b'Away'), (479, b'Towards'), (480, b'To and fro')], default=0)),
                ('movementtype', models.IntegerField(blank=True, choices=[(0, b'None'), (481, b'Straight'), (482, b'Curved'), (483, b'Circle'), (484, b'Zig-zag')], default=0)),
                ('smallmovement', models.IntegerField(blank=True, choices=[(0, b'None'), (485, b'Straighten from bent'), (486, b'Bend fingers'), (487, b'Nod at wrist'), (488, b'Straighten fingers'), (489, b'Open handshape'), (490, b'Close handshape'), (491, b'Wriggle fingers'), (492, b'Crumble fingers')], default=0)),
                ('repetition', models.IntegerField(blank=True, choices=[(0, b'None'), (493, b'Do the movement once'), (494, b'Do the movement twice'), (495, b'Repeat the movement several times')], default=0)),
                ('meaning', models.TextField()),
                ('comments', models.TextField(blank=True)),
                ('video', models.FileField(blank=True, upload_to=b'comments')),
                ('status', models.CharField(choices=[(b'unread', b'unread'), (b'read', b'read'), (b'deleted', b'deleted')], default=b'unread', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SignFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, verbose_name=b'Please give us your comments about this sign. For example: do you think there are other keywords that belong with this sign? Please write your comments or new keyword/s below.')),
                ('kwnotbelong', models.TextField(blank=True, verbose_name=b'Is there a keyword or keyword/s that DO NOT belong with this sign? Please provide the list of keywords below')),
                ('isAuslan', models.IntegerField(choices=[(1, b'yes'), (2, b'Perhaps'), (3, b"Don't know"), (4, b"Don't think so"), (5, b'No'), (0, b'N/A')], verbose_name=b'Is this sign an NGT Sign?')),
                ('whereused', models.CharField(choices=[(b'auswide', b'Australia Wide'), (b'dialectN', b'Dialect Sign (North)'), (b'dialectS', b'Dialect Sign (South)'), (b'nsw', b'New South Wales'), (b'vic', b'Victoria'), (b'qld', b'Queensland'), (b'wa', b'Western Australia'), (b'sa', b'South Australia'), (b'tas', b'Tasmania'), (b'nt', b'Northern Territory'), (b'act', b'Australian Capital Territory'), (b'dk', b"Don't Know"), (b'n/a', b'N/A')], max_length=10, verbose_name=b'Where is this sign used?')),
                ('like', models.IntegerField(choices=[(1, b'yes'), (2, b'A little'), (3, b"Don't care"), (4, b'Not much'), (5, b'No'), (0, b'N/A')], verbose_name=b'Do you like this sign?')),
                ('use', models.IntegerField(choices=[(1, b'yes'), (2, b'Sometimes'), (3, b'Not Often'), (4, b'No'), (0, b'N/A')], verbose_name=b'Do you use this sign?')),
                ('suggested', models.IntegerField(choices=[(1, b'yes'), (2, b'Sometimes'), (3, b"Don't Know"), (4, b'Perhaps'), (5, b'No'), (0, b'N/A')], default=3, verbose_name=b'If this sign is a suggested new sign, would you use it?')),
                ('correct', models.IntegerField(choices=[(1, b'yes'), (2, b'Mostly Correct'), (3, b"Don't Know"), (4, b'Mostly Wrong'), (5, b'No'), (0, b'N/A')], verbose_name=b'Is the information about the sign correct?')),
                ('status', models.CharField(choices=[(b'unread', b'unread'), (b'read', b'read'), (b'deleted', b'deleted')], default=b'unread', max_length=10)),
                ('translation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Translation')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
