# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-07 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import signbank.dictionary.models
from signbank.feedback.models import MissingSignFeedback

def move_fieldchoice_choice_for_class(apps, schema_editor, klass):
    """
    Make a foreign key ref based on the machine_value and the category of the corresponding field
    :param apps:
    :param schema_editor:
    :param klass: the class for which fieldchoices should be moved to foreign keys
    :return:
    """
    klass_old = apps.get_model('feedback', klass.__name__)
    FieldChoice = apps.get_model('dictionary', 'FieldChoice')

    fk_field_names = [f.name[:-3] for f in klass_old._meta.fields if f.name.endswith('_fk')]
    print("FIELDS:", fk_field_names)

    for obj in klass_old.objects.all():
        for field in fk_field_names:
            category = klass._meta.get_field(field+'_fk').field_choice_category
            machine_value = getattr(obj, field)
            print(klass.__name__, obj.pk, "=> Field:", field, "Category:", category, "machine_value:", machine_value)
            try:
                if machine_value:
                    field_choice = FieldChoice.objects.get(field=category, machine_value=machine_value)
                else:
                    field_choice = FieldChoice.objects.get(field=category, machine_value=0)
                setattr(obj, field+'_fk', field_choice)
                obj.save()
            except Exception as e:
                print("INFO: fieldchoice not found", e)


def move_fieldchoice_choice(apps, schema_editor):
    move_fieldchoice_choice_for_class(apps, schema_editor, MissingSignFeedback)


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20181128_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingsignfeedback',
            name='althandshape_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AltHandshape', to='dictionary.FieldChoice', verbose_name='AltHandshape'),
        ),
        migrations.AddField(
            model_name='missingsignfeedback',
            name='direction_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Direction', to='dictionary.FieldChoice', verbose_name='Direction'),
        ),
        migrations.AddField(
            model_name='missingsignfeedback',
            name='handbodycontact_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HandBodyContact', to='dictionary.FieldChoice', verbose_name='HandBodyContact'),
        ),
        migrations.AddField(
            model_name='missingsignfeedback',
            name='handform_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handednessMissingSignFeedback', to='dictionary.FieldChoice', verbose_name='Handedness'),
        ),
        migrations.AddField(
            model_name='missingsignfeedback',
            name='handinteraction_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HandInteraction', to='dictionary.FieldChoice', verbose_name='HandInteraction'),
        ),
        migrations.AddField(
            model_name='missingsignfeedback',
            name='handshape_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Handshape', to='dictionary.FieldChoice', verbose_name='Handshape'),
        ),
        migrations.AddField(
            model_name='missingsignfeedback',
            name='location_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LocationMissingSignFeedback', to='dictionary.FieldChoice', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='missingsignfeedback',
            name='movementtype_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MovementType', to='dictionary.FieldChoice', verbose_name='MovementType'),
        ),
        migrations.AddField(
            model_name='missingsignfeedback',
            name='relativelocation_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Location', to='dictionary.FieldChoice', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='missingsignfeedback',
            name='smallmovement_fk',
            field=signbank.dictionary.models.FieldChoiceForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SmallMovement', to='dictionary.FieldChoice', verbose_name='SmallMovement'),
        ),
        migrations.RunPython(move_fieldchoice_choice),
    ]
