# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-07 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20210107_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingsignfeedback',
            name='althandshape',
        ),
        migrations.RemoveField(
            model_name='missingsignfeedback',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='missingsignfeedback',
            name='handbodycontact',
        ),
        migrations.RemoveField(
            model_name='missingsignfeedback',
            name='handform',
        ),
        migrations.RemoveField(
            model_name='missingsignfeedback',
            name='handinteraction',
        ),
        migrations.RemoveField(
            model_name='missingsignfeedback',
            name='handshape',
        ),
        migrations.RemoveField(
            model_name='missingsignfeedback',
            name='location',
        ),
        migrations.RemoveField(
            model_name='missingsignfeedback',
            name='movementtype',
        ),
        migrations.RemoveField(
            model_name='missingsignfeedback',
            name='relativelocation',
        ),
        migrations.RemoveField(
            model_name='missingsignfeedback',
            name='smallmovement',
        ),
        migrations.RenameField(
            model_name='missingsignfeedback',
            old_name='althandshape_fk',
            new_name='althandshape',
        ),
        migrations.RenameField(
            model_name='missingsignfeedback',
            old_name='direction_fk',
            new_name='direction',
        ),
        migrations.RenameField(
            model_name='missingsignfeedback',
            old_name='handbodycontact_fk',
            new_name='handbodycontact',
        ),
        migrations.RenameField(
            model_name='missingsignfeedback',
            old_name='handform_fk',
            new_name='handform',
        ),
        migrations.RenameField(
            model_name='missingsignfeedback',
            old_name='handinteraction_fk',
            new_name='handinteraction',
        ),
        migrations.RenameField(
            model_name='missingsignfeedback',
            old_name='handshape_fk',
            new_name='handshape',
        ),
        migrations.RenameField(
            model_name='missingsignfeedback',
            old_name='location_fk',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='missingsignfeedback',
            old_name='movementtype_fk',
            new_name='movementtype',
        ),
        migrations.RenameField(
            model_name='missingsignfeedback',
            old_name='relativelocation_fk',
            new_name='relativelocation',
        ),
        migrations.RenameField(
            model_name='missingsignfeedback',
            old_name='smallmovement_fk',
            new_name='smallmovement',
        ),
    ]
