# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-02 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0047_auto_20210602_1006'),
        ('feedback', '0005_auto_20210107_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingsignfeedback',
            name='althandshape_handshapefk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AltHandshape_handshapefk', to='dictionary.Handshape', verbose_name='AltHandshape'),
        ),
        migrations.AddField(
            model_name='missingsignfeedback',
            name='handshape_handshapefk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Handshape_handshapefk', to='dictionary.Handshape', verbose_name='Handshape'),
        ),
    ]
