# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-02 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_auto_20210602_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingsignfeedback',
            name='handshape',
        ),
        migrations.RenameField(
            model_name='missingsignfeedback',
            old_name='handshape_handshapefk',
            new_name='handshape',
        ),
        migrations.RemoveField(
            model_name='missingsignfeedback',
            name='althandshape',
        ),
        migrations.RenameField(
            model_name='missingsignfeedback',
            old_name='althandshape_handshapefk',
            new_name='althandshape',
        ),
    ]
