# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-02 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_auto_20210602_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingsignfeedback',
            name='althandshape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AltHandshape', to='dictionary.Handshape', verbose_name='AltHandshape'),
        ),
        migrations.AlterField(
            model_name='missingsignfeedback',
            name='handshape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Handshape', to='dictionary.Handshape', verbose_name='Handshape'),
        ),
    ]
