# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-01-31 11:53
from __future__ import unicode_literals

from django.db import migrations

def copy_translation_to_gloss_field(apps, schema_editor):
    SignFeedback = apps.get_model('feedback', 'SignFeedback')

    # Copy translation field to gloss field
    for signfeedback in SignFeedback.objects.all():
        if signfeedback.gloss:
            continue
        if not signfeedback.translation:
            continue
        signfeedback.gloss = signfeedback.translation.gloss
        print("Copied signfeedback.translation.gloss to signfeedback.gloss")
        signfeedback.save()

class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_auto_20230125_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morphemefeedback',
            name='translation',
        ),
        migrations.RunPython(copy_translation_to_gloss_field),
    ]
