# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-01-31 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_remove_morphemefeedback_translation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signfeedback',
            name='translation',
        ),
    ]
