name: Deploy
on:
  workflow_dispatch:
jobs:
  deploy:
    strategy:
      matrix:
        runner: [global, vgt]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Pull latest changes
        run: |
          source /var/www/env/bin/activate
          cd /var/www/repo
          sh deploy.sh
