name: Pull latest code

on:
  workflow_dispatch:

jobs:
  git-pull:
    runs-on: self-hosted

    steps:
      - name: Pull latest changes
        run: |
          cd /var/www/repo
          sh deploy.sh
