name: Start acceptance environment

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        type: string
      days_active:
        description: 'Days active'
        required: true
        type: number

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: |
          response = curl -X POST -H "Content-Type: application/json" -d '{"branch": "'"${BRANCH}"'", "days_active": '"${DAYS_ACTIVE}"'}' ${{ secrets.start_environment_url }}
          echo "Response: $response"
        env:
          BRANCH: ${{ inputs.branch }}
          DAYS_ACTIVE: ${{ inputs.days_active }}
